// AUTO-GENERATED by scripts/generate-puzzles.ts — do not edit by hand.
import type { Puzzle } from "../../lib/types";
import p_halloween_easy_01 from "./halloween-easy-01.json";
import p_halloween_medium_01 from "./halloween-medium-01.json";
import p_halloween_hard_01 from "./halloween-hard-01.json";
import p_fall_easy_01 from "./fall-easy-01.json";
import p_fall_medium_01 from "./fall-medium-01.json";
import p_fall_hard_01 from "./fall-hard-01.json";
import p_christmas_easy_01 from "./christmas-easy-01.json";
import p_christmas_medium_01 from "./christmas-medium-01.json";
import p_christmas_hard_01 from "./christmas-hard-01.json";
import p_thanksgiving_easy_01 from "./thanksgiving-easy-01.json";
import p_thanksgiving_easy_02 from "./thanksgiving-easy-02.json";
import p_thanksgiving_medium_01 from "./thanksgiving-medium-01.json";
import p_thanksgiving_medium_02 from "./thanksgiving-medium-02.json";
import p_thanksgiving_hard_01 from "./thanksgiving-hard-01.json";
import p_thanksgiving_large_01 from "./thanksgiving-large-01.json";
import p_winter_easy_01 from "./winter-easy-01.json";
import p_winter_easy_02 from "./winter-easy-02.json";
import p_winter_medium_01 from "./winter-medium-01.json";
import p_winter_medium_02 from "./winter-medium-02.json";
import p_winter_hard_01 from "./winter-hard-01.json";
import p_winter_large_01 from "./winter-large-01.json";
import p_valentines_easy_01 from "./valentines-easy-01.json";
import p_valentines_easy_02 from "./valentines-easy-02.json";
import p_valentines_medium_01 from "./valentines-medium-01.json";
import p_valentines_medium_02 from "./valentines-medium-02.json";
import p_valentines_hard_01 from "./valentines-hard-01.json";
import p_valentines_large_01 from "./valentines-large-01.json";
import p_easter_easy_01 from "./easter-easy-01.json";
import p_easter_easy_02 from "./easter-easy-02.json";
import p_easter_medium_01 from "./easter-medium-01.json";
import p_easter_medium_02 from "./easter-medium-02.json";
import p_easter_hard_01 from "./easter-hard-01.json";
import p_easter_large_01 from "./easter-large-01.json";
import p_animals_easy_01 from "./animals-easy-01.json";
import p_animals_medium_01 from "./animals-medium-01.json";
import p_animals_hard_01 from "./animals-hard-01.json";
import p_space_easy_01 from "./space-easy-01.json";
import p_space_medium_01 from "./space-medium-01.json";
import p_space_hard_01 from "./space-hard-01.json";
import p_sports_easy_01 from "./sports-easy-01.json";
import p_sports_medium_01 from "./sports-medium-01.json";
import p_food_easy_01 from "./food-easy-01.json";
import p_food_medium_01 from "./food-medium-01.json";
import p_ocean_easy_01 from "./ocean-easy-01.json";
import p_ocean_medium_01 from "./ocean-medium-01.json";
import p_ocean_hard_01 from "./ocean-hard-01.json";
import p_dogs_easy_01 from "./dogs-easy-01.json";
import p_dogs_medium_01 from "./dogs-medium-01.json";
import p_cats_easy_01 from "./cats-easy-01.json";
import p_cats_medium_01 from "./cats-medium-01.json";
import p_travel_easy_01 from "./travel-easy-01.json";
import p_travel_medium_01 from "./travel-medium-01.json";
import p_music_easy_01 from "./music-easy-01.json";
import p_music_medium_01 from "./music-medium-01.json";
import p_garden_easy_01 from "./garden-easy-01.json";
import p_garden_medium_01 from "./garden-medium-01.json";
import p_garden_hard_01 from "./garden-hard-01.json";
import p_bible_easy_01 from "./bible-easy-01.json";
import p_bible_easy_02 from "./bible-easy-02.json";
import p_bible_medium_01 from "./bible-medium-01.json";
import p_bible_medium_02 from "./bible-medium-02.json";
import p_bible_hard_01 from "./bible-hard-01.json";
import p_bible_large_01 from "./bible-large-01.json";
import p_golf_easy_01 from "./golf-easy-01.json";
import p_golf_easy_02 from "./golf-easy-02.json";
import p_golf_medium_01 from "./golf-medium-01.json";
import p_golf_medium_02 from "./golf-medium-02.json";
import p_golf_hard_01 from "./golf-hard-01.json";
import p_golf_large_01 from "./golf-large-01.json";
import p_baseball_easy_01 from "./baseball-easy-01.json";
import p_baseball_easy_02 from "./baseball-easy-02.json";
import p_baseball_medium_01 from "./baseball-medium-01.json";
import p_baseball_medium_02 from "./baseball-medium-02.json";
import p_baseball_hard_01 from "./baseball-hard-01.json";
import p_baseball_large_01 from "./baseball-large-01.json";
import p_tennis_easy_01 from "./tennis-easy-01.json";
import p_tennis_easy_02 from "./tennis-easy-02.json";
import p_tennis_medium_01 from "./tennis-medium-01.json";
import p_tennis_medium_02 from "./tennis-medium-02.json";
import p_tennis_hard_01 from "./tennis-hard-01.json";
import p_tennis_large_01 from "./tennis-large-01.json";
import p_fishing_easy_01 from "./fishing-easy-01.json";
import p_fishing_easy_02 from "./fishing-easy-02.json";
import p_fishing_medium_01 from "./fishing-medium-01.json";
import p_fishing_medium_02 from "./fishing-medium-02.json";
import p_fishing_hard_01 from "./fishing-hard-01.json";
import p_fishing_large_01 from "./fishing-large-01.json";
import p_baking_easy_01 from "./baking-easy-01.json";
import p_baking_easy_02 from "./baking-easy-02.json";
import p_baking_medium_01 from "./baking-medium-01.json";
import p_baking_medium_02 from "./baking-medium-02.json";
import p_baking_hard_01 from "./baking-hard-01.json";
import p_baking_large_01 from "./baking-large-01.json";
import p_desserts_easy_01 from "./desserts-easy-01.json";
import p_desserts_easy_02 from "./desserts-easy-02.json";
import p_desserts_medium_01 from "./desserts-medium-01.json";
import p_desserts_medium_02 from "./desserts-medium-02.json";
import p_desserts_hard_01 from "./desserts-hard-01.json";
import p_desserts_large_01 from "./desserts-large-01.json";
import p_herbs_easy_01 from "./herbs-easy-01.json";
import p_herbs_easy_02 from "./herbs-easy-02.json";
import p_herbs_medium_01 from "./herbs-medium-01.json";
import p_herbs_medium_02 from "./herbs-medium-02.json";
import p_herbs_hard_01 from "./herbs-hard-01.json";
import p_herbs_large_01 from "./herbs-large-01.json";
import p_fruits_easy_01 from "./fruits-easy-01.json";
import p_fruits_easy_02 from "./fruits-easy-02.json";
import p_fruits_medium_01 from "./fruits-medium-01.json";
import p_fruits_medium_02 from "./fruits-medium-02.json";
import p_fruits_hard_01 from "./fruits-hard-01.json";
import p_fruits_large_01 from "./fruits-large-01.json";
import p_instruments_easy_01 from "./instruments-easy-01.json";
import p_instruments_easy_02 from "./instruments-easy-02.json";
import p_instruments_medium_01 from "./instruments-medium-01.json";
import p_instruments_medium_02 from "./instruments-medium-02.json";
import p_instruments_hard_01 from "./instruments-hard-01.json";
import p_instruments_large_01 from "./instruments-large-01.json";
import p_jazz_easy_01 from "./jazz-easy-01.json";
import p_jazz_easy_02 from "./jazz-easy-02.json";
import p_jazz_medium_01 from "./jazz-medium-01.json";
import p_jazz_medium_02 from "./jazz-medium-02.json";
import p_jazz_hard_01 from "./jazz-hard-01.json";
import p_jazz_large_01 from "./jazz-large-01.json";
import p_classical_easy_01 from "./classical-easy-01.json";
import p_classical_easy_02 from "./classical-easy-02.json";
import p_classical_medium_01 from "./classical-medium-01.json";
import p_classical_medium_02 from "./classical-medium-02.json";
import p_classical_hard_01 from "./classical-hard-01.json";
import p_classical_large_01 from "./classical-large-01.json";
import p_music_terms_easy_01 from "./music-terms-easy-01.json";
import p_music_terms_easy_02 from "./music-terms-easy-02.json";
import p_music_terms_medium_01 from "./music-terms-medium-01.json";
import p_music_terms_medium_02 from "./music-terms-medium-02.json";
import p_music_terms_hard_01 from "./music-terms-hard-01.json";
import p_music_terms_large_01 from "./music-terms-large-01.json";
import p_new_year_easy_01 from "./new-year-easy-01.json";
import p_new_year_easy_02 from "./new-year-easy-02.json";
import p_new_year_medium_01 from "./new-year-medium-01.json";
import p_new_year_medium_02 from "./new-year-medium-02.json";
import p_new_year_hard_01 from "./new-year-hard-01.json";
import p_new_year_large_01 from "./new-year-large-01.json";
import p_st_patricks_easy_01 from "./st-patricks-easy-01.json";
import p_st_patricks_easy_02 from "./st-patricks-easy-02.json";
import p_st_patricks_medium_01 from "./st-patricks-medium-01.json";
import p_st_patricks_medium_02 from "./st-patricks-medium-02.json";
import p_st_patricks_hard_01 from "./st-patricks-hard-01.json";
import p_st_patricks_large_01 from "./st-patricks-large-01.json";
import p_mothers_day_easy_01 from "./mothers-day-easy-01.json";
import p_mothers_day_easy_02 from "./mothers-day-easy-02.json";
import p_mothers_day_medium_01 from "./mothers-day-medium-01.json";
import p_mothers_day_medium_02 from "./mothers-day-medium-02.json";
import p_mothers_day_hard_01 from "./mothers-day-hard-01.json";
import p_mothers_day_large_01 from "./mothers-day-large-01.json";
import p_fathers_day_easy_01 from "./fathers-day-easy-01.json";
import p_fathers_day_easy_02 from "./fathers-day-easy-02.json";
import p_fathers_day_medium_01 from "./fathers-day-medium-01.json";
import p_fathers_day_medium_02 from "./fathers-day-medium-02.json";
import p_fathers_day_hard_01 from "./fathers-day-hard-01.json";
import p_fathers_day_large_01 from "./fathers-day-large-01.json";
import p_independence_day_easy_01 from "./independence-day-easy-01.json";
import p_independence_day_easy_02 from "./independence-day-easy-02.json";
import p_independence_day_medium_01 from "./independence-day-medium-01.json";
import p_independence_day_medium_02 from "./independence-day-medium-02.json";
import p_independence_day_hard_01 from "./independence-day-hard-01.json";
import p_independence_day_large_01 from "./independence-day-large-01.json";
import p_spring_easy_01 from "./spring-easy-01.json";
import p_spring_easy_02 from "./spring-easy-02.json";
import p_spring_medium_01 from "./spring-medium-01.json";
import p_spring_medium_02 from "./spring-medium-02.json";
import p_spring_hard_01 from "./spring-hard-01.json";
import p_spring_large_01 from "./spring-large-01.json";
import p_summer_easy_01 from "./summer-easy-01.json";
import p_summer_easy_02 from "./summer-easy-02.json";
import p_summer_medium_01 from "./summer-medium-01.json";
import p_summer_medium_02 from "./summer-medium-02.json";
import p_summer_hard_01 from "./summer-hard-01.json";
import p_summer_large_01 from "./summer-large-01.json";
import p_vegetables_easy_01 from "./vegetables-easy-01.json";
import p_vegetables_easy_02 from "./vegetables-easy-02.json";
import p_vegetables_medium_01 from "./vegetables-medium-01.json";
import p_vegetables_medium_02 from "./vegetables-medium-02.json";
import p_vegetables_hard_01 from "./vegetables-hard-01.json";
import p_vegetables_large_01 from "./vegetables-large-01.json";
import p_breakfast_easy_01 from "./breakfast-easy-01.json";
import p_breakfast_easy_02 from "./breakfast-easy-02.json";
import p_breakfast_medium_01 from "./breakfast-medium-01.json";
import p_breakfast_medium_02 from "./breakfast-medium-02.json";
import p_breakfast_hard_01 from "./breakfast-hard-01.json";
import p_breakfast_large_01 from "./breakfast-large-01.json";
import p_coffee_tea_easy_01 from "./coffee-tea-easy-01.json";
import p_coffee_tea_easy_02 from "./coffee-tea-easy-02.json";
import p_coffee_tea_medium_01 from "./coffee-tea-medium-01.json";
import p_coffee_tea_medium_02 from "./coffee-tea-medium-02.json";
import p_coffee_tea_hard_01 from "./coffee-tea-hard-01.json";
import p_coffee_tea_large_01 from "./coffee-tea-large-01.json";
import p_kitchen_easy_01 from "./kitchen-easy-01.json";
import p_kitchen_easy_02 from "./kitchen-easy-02.json";
import p_kitchen_medium_01 from "./kitchen-medium-01.json";
import p_kitchen_medium_02 from "./kitchen-medium-02.json";
import p_kitchen_hard_01 from "./kitchen-hard-01.json";
import p_kitchen_large_01 from "./kitchen-large-01.json";
import p_birds_easy_01 from "./birds-easy-01.json";
import p_birds_easy_02 from "./birds-easy-02.json";
import p_birds_medium_01 from "./birds-medium-01.json";
import p_birds_medium_02 from "./birds-medium-02.json";
import p_birds_hard_01 from "./birds-hard-01.json";
import p_birds_large_01 from "./birds-large-01.json";
import p_flowers_easy_01 from "./flowers-easy-01.json";
import p_flowers_easy_02 from "./flowers-easy-02.json";
import p_flowers_medium_01 from "./flowers-medium-01.json";
import p_flowers_medium_02 from "./flowers-medium-02.json";
import p_flowers_hard_01 from "./flowers-hard-01.json";
import p_flowers_large_01 from "./flowers-large-01.json";
import p_trees_easy_01 from "./trees-easy-01.json";
import p_trees_easy_02 from "./trees-easy-02.json";
import p_trees_medium_01 from "./trees-medium-01.json";
import p_trees_medium_02 from "./trees-medium-02.json";
import p_trees_hard_01 from "./trees-hard-01.json";
import p_trees_large_01 from "./trees-large-01.json";
import p_weather_easy_01 from "./weather-easy-01.json";
import p_weather_easy_02 from "./weather-easy-02.json";
import p_weather_medium_01 from "./weather-medium-01.json";
import p_weather_medium_02 from "./weather-medium-02.json";
import p_weather_hard_01 from "./weather-hard-01.json";
import p_weather_large_01 from "./weather-large-01.json";
import p_us_states_easy_01 from "./us-states-easy-01.json";
import p_us_states_easy_02 from "./us-states-easy-02.json";
import p_us_states_medium_01 from "./us-states-medium-01.json";
import p_us_states_medium_02 from "./us-states-medium-02.json";
import p_us_states_hard_01 from "./us-states-hard-01.json";
import p_us_states_large_01 from "./us-states-large-01.json";
import p_world_capitals_easy_01 from "./world-capitals-easy-01.json";
import p_world_capitals_easy_02 from "./world-capitals-easy-02.json";
import p_world_capitals_medium_01 from "./world-capitals-medium-01.json";
import p_world_capitals_medium_02 from "./world-capitals-medium-02.json";
import p_world_capitals_hard_01 from "./world-capitals-hard-01.json";
import p_world_capitals_large_01 from "./world-capitals-large-01.json";
import p_human_body_easy_01 from "./human-body-easy-01.json";
import p_human_body_easy_02 from "./human-body-easy-02.json";
import p_human_body_medium_01 from "./human-body-medium-01.json";
import p_human_body_medium_02 from "./human-body-medium-02.json";
import p_human_body_hard_01 from "./human-body-hard-01.json";
import p_human_body_large_01 from "./human-body-large-01.json";
import p_camping_easy_01 from "./camping-easy-01.json";
import p_camping_easy_02 from "./camping-easy-02.json";
import p_camping_medium_01 from "./camping-medium-01.json";
import p_camping_medium_02 from "./camping-medium-02.json";
import p_camping_hard_01 from "./camping-hard-01.json";
import p_camping_large_01 from "./camping-large-01.json";
import p_horses_easy_01 from "./horses-easy-01.json";
import p_horses_easy_02 from "./horses-easy-02.json";
import p_horses_medium_01 from "./horses-medium-01.json";
import p_horses_medium_02 from "./horses-medium-02.json";
import p_horses_hard_01 from "./horses-hard-01.json";
import p_horses_large_01 from "./horses-large-01.json";
import p_cars_easy_01 from "./cars-easy-01.json";
import p_cars_easy_02 from "./cars-easy-02.json";
import p_cars_medium_01 from "./cars-medium-01.json";
import p_cars_medium_02 from "./cars-medium-02.json";
import p_cars_hard_01 from "./cars-hard-01.json";
import p_cars_large_01 from "./cars-large-01.json";
import p_trains_easy_01 from "./trains-easy-01.json";
import p_trains_easy_02 from "./trains-easy-02.json";
import p_trains_medium_01 from "./trains-medium-01.json";
import p_trains_medium_02 from "./trains-medium-02.json";
import p_trains_hard_01 from "./trains-hard-01.json";
import p_trains_large_01 from "./trains-large-01.json";
import p_airplanes_easy_01 from "./airplanes-easy-01.json";
import p_airplanes_easy_02 from "./airplanes-easy-02.json";
import p_airplanes_medium_01 from "./airplanes-medium-01.json";
import p_airplanes_medium_02 from "./airplanes-medium-02.json";
import p_airplanes_hard_01 from "./airplanes-hard-01.json";
import p_airplanes_large_01 from "./airplanes-large-01.json";
import p_farming_easy_01 from "./farming-easy-01.json";
import p_farming_easy_02 from "./farming-easy-02.json";
import p_farming_medium_01 from "./farming-medium-01.json";
import p_farming_medium_02 from "./farming-medium-02.json";
import p_farming_hard_01 from "./farming-hard-01.json";
import p_farming_large_01 from "./farming-large-01.json";
import p_beach_easy_01 from "./beach-easy-01.json";
import p_beach_easy_02 from "./beach-easy-02.json";
import p_beach_medium_01 from "./beach-medium-01.json";
import p_beach_medium_02 from "./beach-medium-02.json";
import p_beach_hard_01 from "./beach-hard-01.json";
import p_beach_large_01 from "./beach-large-01.json";
import p_mountains_easy_01 from "./mountains-easy-01.json";
import p_mountains_easy_02 from "./mountains-easy-02.json";
import p_mountains_medium_01 from "./mountains-medium-01.json";
import p_mountains_medium_02 from "./mountains-medium-02.json";
import p_mountains_hard_01 from "./mountains-hard-01.json";
import p_mountains_large_01 from "./mountains-large-01.json";
import p_lakes_easy_01 from "./lakes-easy-01.json";
import p_lakes_easy_02 from "./lakes-easy-02.json";
import p_lakes_medium_01 from "./lakes-medium-01.json";
import p_lakes_medium_02 from "./lakes-medium-02.json";
import p_lakes_hard_01 from "./lakes-hard-01.json";
import p_lakes_large_01 from "./lakes-large-01.json";
import p_school_easy_01 from "./school-easy-01.json";
import p_school_easy_02 from "./school-easy-02.json";
import p_school_medium_01 from "./school-medium-01.json";
import p_school_medium_02 from "./school-medium-02.json";
import p_school_hard_01 from "./school-hard-01.json";
import p_school_large_01 from "./school-large-01.json";
import p_jobs_easy_01 from "./jobs-easy-01.json";
import p_jobs_easy_02 from "./jobs-easy-02.json";
import p_jobs_medium_01 from "./jobs-medium-01.json";
import p_jobs_medium_02 from "./jobs-medium-02.json";
import p_jobs_hard_01 from "./jobs-hard-01.json";
import p_jobs_large_01 from "./jobs-large-01.json";
import p_friendship_easy_01 from "./friendship-easy-01.json";
import p_friendship_easy_02 from "./friendship-easy-02.json";
import p_friendship_medium_01 from "./friendship-medium-01.json";
import p_friendship_medium_02 from "./friendship-medium-02.json";
import p_friendship_hard_01 from "./friendship-hard-01.json";
import p_friendship_large_01 from "./friendship-large-01.json";
import p_hard_pack_hard_01 from "./hard-pack-hard-01.json";
import p_hard_pack_hard_02 from "./hard-pack-hard-02.json";
import p_hard_pack_hard_03 from "./hard-pack-hard-03.json";
import p_large_print_pack_large_01 from "./large-print-pack-large-01.json";
import p_large_print_pack_large_02 from "./large-print-pack-large-02.json";
import p_large_print_pack_large_03 from "./large-print-pack-large-03.json";
import p_large_print_pack_large_04 from "./large-print-pack-large-04.json";

export const puzzles = [
  p_halloween_easy_01,
  p_halloween_medium_01,
  p_halloween_hard_01,
  p_fall_easy_01,
  p_fall_medium_01,
  p_fall_hard_01,
  p_christmas_easy_01,
  p_christmas_medium_01,
  p_christmas_hard_01,
  p_thanksgiving_easy_01,
  p_thanksgiving_easy_02,
  p_thanksgiving_medium_01,
  p_thanksgiving_medium_02,
  p_thanksgiving_hard_01,
  p_thanksgiving_large_01,
  p_winter_easy_01,
  p_winter_easy_02,
  p_winter_medium_01,
  p_winter_medium_02,
  p_winter_hard_01,
  p_winter_large_01,
  p_valentines_easy_01,
  p_valentines_easy_02,
  p_valentines_medium_01,
  p_valentines_medium_02,
  p_valentines_hard_01,
  p_valentines_large_01,
  p_easter_easy_01,
  p_easter_easy_02,
  p_easter_medium_01,
  p_easter_medium_02,
  p_easter_hard_01,
  p_easter_large_01,
  p_animals_easy_01,
  p_animals_medium_01,
  p_animals_hard_01,
  p_space_easy_01,
  p_space_medium_01,
  p_space_hard_01,
  p_sports_easy_01,
  p_sports_medium_01,
  p_food_easy_01,
  p_food_medium_01,
  p_ocean_easy_01,
  p_ocean_medium_01,
  p_ocean_hard_01,
  p_dogs_easy_01,
  p_dogs_medium_01,
  p_cats_easy_01,
  p_cats_medium_01,
  p_travel_easy_01,
  p_travel_medium_01,
  p_music_easy_01,
  p_music_medium_01,
  p_garden_easy_01,
  p_garden_medium_01,
  p_garden_hard_01,
  p_bible_easy_01,
  p_bible_easy_02,
  p_bible_medium_01,
  p_bible_medium_02,
  p_bible_hard_01,
  p_bible_large_01,
  p_golf_easy_01,
  p_golf_easy_02,
  p_golf_medium_01,
  p_golf_medium_02,
  p_golf_hard_01,
  p_golf_large_01,
  p_baseball_easy_01,
  p_baseball_easy_02,
  p_baseball_medium_01,
  p_baseball_medium_02,
  p_baseball_hard_01,
  p_baseball_large_01,
  p_tennis_easy_01,
  p_tennis_easy_02,
  p_tennis_medium_01,
  p_tennis_medium_02,
  p_tennis_hard_01,
  p_tennis_large_01,
  p_fishing_easy_01,
  p_fishing_easy_02,
  p_fishing_medium_01,
  p_fishing_medium_02,
  p_fishing_hard_01,
  p_fishing_large_01,
  p_baking_easy_01,
  p_baking_easy_02,
  p_baking_medium_01,
  p_baking_medium_02,
  p_baking_hard_01,
  p_baking_large_01,
  p_desserts_easy_01,
  p_desserts_easy_02,
  p_desserts_medium_01,
  p_desserts_medium_02,
  p_desserts_hard_01,
  p_desserts_large_01,
  p_herbs_easy_01,
  p_herbs_easy_02,
  p_herbs_medium_01,
  p_herbs_medium_02,
  p_herbs_hard_01,
  p_herbs_large_01,
  p_fruits_easy_01,
  p_fruits_easy_02,
  p_fruits_medium_01,
  p_fruits_medium_02,
  p_fruits_hard_01,
  p_fruits_large_01,
  p_instruments_easy_01,
  p_instruments_easy_02,
  p_instruments_medium_01,
  p_instruments_medium_02,
  p_instruments_hard_01,
  p_instruments_large_01,
  p_jazz_easy_01,
  p_jazz_easy_02,
  p_jazz_medium_01,
  p_jazz_medium_02,
  p_jazz_hard_01,
  p_jazz_large_01,
  p_classical_easy_01,
  p_classical_easy_02,
  p_classical_medium_01,
  p_classical_medium_02,
  p_classical_hard_01,
  p_classical_large_01,
  p_music_terms_easy_01,
  p_music_terms_easy_02,
  p_music_terms_medium_01,
  p_music_terms_medium_02,
  p_music_terms_hard_01,
  p_music_terms_large_01,
  p_new_year_easy_01,
  p_new_year_easy_02,
  p_new_year_medium_01,
  p_new_year_medium_02,
  p_new_year_hard_01,
  p_new_year_large_01,
  p_st_patricks_easy_01,
  p_st_patricks_easy_02,
  p_st_patricks_medium_01,
  p_st_patricks_medium_02,
  p_st_patricks_hard_01,
  p_st_patricks_large_01,
  p_mothers_day_easy_01,
  p_mothers_day_easy_02,
  p_mothers_day_medium_01,
  p_mothers_day_medium_02,
  p_mothers_day_hard_01,
  p_mothers_day_large_01,
  p_fathers_day_easy_01,
  p_fathers_day_easy_02,
  p_fathers_day_medium_01,
  p_fathers_day_medium_02,
  p_fathers_day_hard_01,
  p_fathers_day_large_01,
  p_independence_day_easy_01,
  p_independence_day_easy_02,
  p_independence_day_medium_01,
  p_independence_day_medium_02,
  p_independence_day_hard_01,
  p_independence_day_large_01,
  p_spring_easy_01,
  p_spring_easy_02,
  p_spring_medium_01,
  p_spring_medium_02,
  p_spring_hard_01,
  p_spring_large_01,
  p_summer_easy_01,
  p_summer_easy_02,
  p_summer_medium_01,
  p_summer_medium_02,
  p_summer_hard_01,
  p_summer_large_01,
  p_vegetables_easy_01,
  p_vegetables_easy_02,
  p_vegetables_medium_01,
  p_vegetables_medium_02,
  p_vegetables_hard_01,
  p_vegetables_large_01,
  p_breakfast_easy_01,
  p_breakfast_easy_02,
  p_breakfast_medium_01,
  p_breakfast_medium_02,
  p_breakfast_hard_01,
  p_breakfast_large_01,
  p_coffee_tea_easy_01,
  p_coffee_tea_easy_02,
  p_coffee_tea_medium_01,
  p_coffee_tea_medium_02,
  p_coffee_tea_hard_01,
  p_coffee_tea_large_01,
  p_kitchen_easy_01,
  p_kitchen_easy_02,
  p_kitchen_medium_01,
  p_kitchen_medium_02,
  p_kitchen_hard_01,
  p_kitchen_large_01,
  p_birds_easy_01,
  p_birds_easy_02,
  p_birds_medium_01,
  p_birds_medium_02,
  p_birds_hard_01,
  p_birds_large_01,
  p_flowers_easy_01,
  p_flowers_easy_02,
  p_flowers_medium_01,
  p_flowers_medium_02,
  p_flowers_hard_01,
  p_flowers_large_01,
  p_trees_easy_01,
  p_trees_easy_02,
  p_trees_medium_01,
  p_trees_medium_02,
  p_trees_hard_01,
  p_trees_large_01,
  p_weather_easy_01,
  p_weather_easy_02,
  p_weather_medium_01,
  p_weather_medium_02,
  p_weather_hard_01,
  p_weather_large_01,
  p_us_states_easy_01,
  p_us_states_easy_02,
  p_us_states_medium_01,
  p_us_states_medium_02,
  p_us_states_hard_01,
  p_us_states_large_01,
  p_world_capitals_easy_01,
  p_world_capitals_easy_02,
  p_world_capitals_medium_01,
  p_world_capitals_medium_02,
  p_world_capitals_hard_01,
  p_world_capitals_large_01,
  p_human_body_easy_01,
  p_human_body_easy_02,
  p_human_body_medium_01,
  p_human_body_medium_02,
  p_human_body_hard_01,
  p_human_body_large_01,
  p_camping_easy_01,
  p_camping_easy_02,
  p_camping_medium_01,
  p_camping_medium_02,
  p_camping_hard_01,
  p_camping_large_01,
  p_horses_easy_01,
  p_horses_easy_02,
  p_horses_medium_01,
  p_horses_medium_02,
  p_horses_hard_01,
  p_horses_large_01,
  p_cars_easy_01,
  p_cars_easy_02,
  p_cars_medium_01,
  p_cars_medium_02,
  p_cars_hard_01,
  p_cars_large_01,
  p_trains_easy_01,
  p_trains_easy_02,
  p_trains_medium_01,
  p_trains_medium_02,
  p_trains_hard_01,
  p_trains_large_01,
  p_airplanes_easy_01,
  p_airplanes_easy_02,
  p_airplanes_medium_01,
  p_airplanes_medium_02,
  p_airplanes_hard_01,
  p_airplanes_large_01,
  p_farming_easy_01,
  p_farming_easy_02,
  p_farming_medium_01,
  p_farming_medium_02,
  p_farming_hard_01,
  p_farming_large_01,
  p_beach_easy_01,
  p_beach_easy_02,
  p_beach_medium_01,
  p_beach_medium_02,
  p_beach_hard_01,
  p_beach_large_01,
  p_mountains_easy_01,
  p_mountains_easy_02,
  p_mountains_medium_01,
  p_mountains_medium_02,
  p_mountains_hard_01,
  p_mountains_large_01,
  p_lakes_easy_01,
  p_lakes_easy_02,
  p_lakes_medium_01,
  p_lakes_medium_02,
  p_lakes_hard_01,
  p_lakes_large_01,
  p_school_easy_01,
  p_school_easy_02,
  p_school_medium_01,
  p_school_medium_02,
  p_school_hard_01,
  p_school_large_01,
  p_jobs_easy_01,
  p_jobs_easy_02,
  p_jobs_medium_01,
  p_jobs_medium_02,
  p_jobs_hard_01,
  p_jobs_large_01,
  p_friendship_easy_01,
  p_friendship_easy_02,
  p_friendship_medium_01,
  p_friendship_medium_02,
  p_friendship_hard_01,
  p_friendship_large_01,
  p_hard_pack_hard_01,
  p_hard_pack_hard_02,
  p_hard_pack_hard_03,
  p_large_print_pack_large_01,
  p_large_print_pack_large_02,
  p_large_print_pack_large_03,
  p_large_print_pack_large_04,
] as Puzzle[];
