// AUTO-GENERATED by scripts/generate-puzzles.ts — do not edit by hand.
import type { Puzzle } from "../../lib/types";
import p_halloween_easy_01 from "./halloween-easy-01.json";
import p_halloween_medium_01 from "./halloween-medium-01.json";
import p_halloween_hard_01 from "./halloween-hard-01.json";
import p_animals_easy_01 from "./animals-easy-01.json";
import p_animals_medium_01 from "./animals-medium-01.json";
import p_large_print_pack_large_01 from "./large-print-pack-large-01.json";
import p_large_print_pack_large_02 from "./large-print-pack-large-02.json";

export const puzzles = [
  p_halloween_easy_01,
  p_halloween_medium_01,
  p_halloween_hard_01,
  p_animals_easy_01,
  p_animals_medium_01,
  p_large_print_pack_large_01,
  p_large_print_pack_large_02,
] as Puzzle[];
