// AUTO-GENERATED by scripts/generate-puzzles.ts — do not edit by hand.
import type { Puzzle } from "../../lib/types";
import p_airplanes_easy_01 from "./airplanes-easy-01.json";
import p_airplanes_easy_02 from "./airplanes-easy-02.json";
import p_airplanes_hard_01 from "./airplanes-hard-01.json";
import p_airplanes_large_01 from "./airplanes-large-01.json";
import p_airplanes_medium_01 from "./airplanes-medium-01.json";
import p_airplanes_medium_02 from "./airplanes-medium-02.json";
import p_american_history_easy_01 from "./american-history-easy-01.json";
import p_american_history_easy_02 from "./american-history-easy-02.json";
import p_american_history_hard_01 from "./american-history-hard-01.json";
import p_american_history_large_01 from "./american-history-large-01.json";
import p_american_history_medium_01 from "./american-history-medium-01.json";
import p_american_history_medium_02 from "./american-history-medium-02.json";
import p_animals_easy_01 from "./animals-easy-01.json";
import p_animals_easy_02 from "./animals-easy-02.json";
import p_animals_easy_03 from "./animals-easy-03.json";
import p_animals_hard_01 from "./animals-hard-01.json";
import p_animals_hard_02 from "./animals-hard-02.json";
import p_animals_hard_03 from "./animals-hard-03.json";
import p_animals_large_01 from "./animals-large-01.json";
import p_animals_large_02 from "./animals-large-02.json";
import p_animals_medium_01 from "./animals-medium-01.json";
import p_animals_medium_02 from "./animals-medium-02.json";
import p_animals_medium_03 from "./animals-medium-03.json";
import p_architecture_easy_01 from "./architecture-easy-01.json";
import p_architecture_easy_02 from "./architecture-easy-02.json";
import p_architecture_hard_01 from "./architecture-hard-01.json";
import p_architecture_large_01 from "./architecture-large-01.json";
import p_architecture_medium_01 from "./architecture-medium-01.json";
import p_architecture_medium_02 from "./architecture-medium-02.json";
import p_astronomy_easy_01 from "./astronomy-easy-01.json";
import p_astronomy_easy_02 from "./astronomy-easy-02.json";
import p_astronomy_hard_01 from "./astronomy-hard-01.json";
import p_astronomy_large_01 from "./astronomy-large-01.json";
import p_astronomy_medium_01 from "./astronomy-medium-01.json";
import p_astronomy_medium_02 from "./astronomy-medium-02.json";
import p_baking_easy_01 from "./baking-easy-01.json";
import p_baking_easy_02 from "./baking-easy-02.json";
import p_baking_hard_01 from "./baking-hard-01.json";
import p_baking_large_01 from "./baking-large-01.json";
import p_baking_medium_01 from "./baking-medium-01.json";
import p_baking_medium_02 from "./baking-medium-02.json";
import p_baseball_easy_01 from "./baseball-easy-01.json";
import p_baseball_easy_02 from "./baseball-easy-02.json";
import p_baseball_hard_01 from "./baseball-hard-01.json";
import p_baseball_large_01 from "./baseball-large-01.json";
import p_baseball_medium_01 from "./baseball-medium-01.json";
import p_baseball_medium_02 from "./baseball-medium-02.json";
import p_basketball_easy_01 from "./basketball-easy-01.json";
import p_basketball_easy_02 from "./basketball-easy-02.json";
import p_basketball_hard_01 from "./basketball-hard-01.json";
import p_basketball_large_01 from "./basketball-large-01.json";
import p_basketball_medium_01 from "./basketball-medium-01.json";
import p_basketball_medium_02 from "./basketball-medium-02.json";
import p_beach_easy_01 from "./beach-easy-01.json";
import p_beach_easy_02 from "./beach-easy-02.json";
import p_beach_hard_01 from "./beach-hard-01.json";
import p_beach_large_01 from "./beach-large-01.json";
import p_beach_medium_01 from "./beach-medium-01.json";
import p_beach_medium_02 from "./beach-medium-02.json";
import p_bible_easy_01 from "./bible-easy-01.json";
import p_bible_easy_02 from "./bible-easy-02.json";
import p_bible_easy_03 from "./bible-easy-03.json";
import p_bible_easy_04 from "./bible-easy-04.json";
import p_bible_hard_01 from "./bible-hard-01.json";
import p_bible_hard_02 from "./bible-hard-02.json";
import p_bible_hard_03 from "./bible-hard-03.json";
import p_bible_large_01 from "./bible-large-01.json";
import p_bible_large_02 from "./bible-large-02.json";
import p_bible_medium_01 from "./bible-medium-01.json";
import p_bible_medium_02 from "./bible-medium-02.json";
import p_bible_medium_03 from "./bible-medium-03.json";
import p_bible_medium_04 from "./bible-medium-04.json";
import p_birds_easy_01 from "./birds-easy-01.json";
import p_birds_easy_02 from "./birds-easy-02.json";
import p_birds_hard_01 from "./birds-hard-01.json";
import p_birds_large_01 from "./birds-large-01.json";
import p_birds_medium_01 from "./birds-medium-01.json";
import p_birds_medium_02 from "./birds-medium-02.json";
import p_birthday_easy_01 from "./birthday-easy-01.json";
import p_birthday_easy_02 from "./birthday-easy-02.json";
import p_birthday_hard_01 from "./birthday-hard-01.json";
import p_birthday_large_01 from "./birthday-large-01.json";
import p_birthday_medium_01 from "./birthday-medium-01.json";
import p_birthday_medium_02 from "./birthday-medium-02.json";
import p_board_games_easy_01 from "./board-games-easy-01.json";
import p_board_games_easy_02 from "./board-games-easy-02.json";
import p_board_games_hard_01 from "./board-games-hard-01.json";
import p_board_games_large_01 from "./board-games-large-01.json";
import p_board_games_medium_01 from "./board-games-medium-01.json";
import p_board_games_medium_02 from "./board-games-medium-02.json";
import p_breakfast_easy_01 from "./breakfast-easy-01.json";
import p_breakfast_easy_02 from "./breakfast-easy-02.json";
import p_breakfast_hard_01 from "./breakfast-hard-01.json";
import p_breakfast_large_01 from "./breakfast-large-01.json";
import p_breakfast_medium_01 from "./breakfast-medium-01.json";
import p_breakfast_medium_02 from "./breakfast-medium-02.json";
import p_camping_easy_01 from "./camping-easy-01.json";
import p_camping_easy_02 from "./camping-easy-02.json";
import p_camping_hard_01 from "./camping-hard-01.json";
import p_camping_large_01 from "./camping-large-01.json";
import p_camping_medium_01 from "./camping-medium-01.json";
import p_camping_medium_02 from "./camping-medium-02.json";
import p_cars_easy_01 from "./cars-easy-01.json";
import p_cars_easy_02 from "./cars-easy-02.json";
import p_cars_hard_01 from "./cars-hard-01.json";
import p_cars_large_01 from "./cars-large-01.json";
import p_cars_medium_01 from "./cars-medium-01.json";
import p_cars_medium_02 from "./cars-medium-02.json";
import p_cats_easy_01 from "./cats-easy-01.json";
import p_cats_easy_02 from "./cats-easy-02.json";
import p_cats_hard_01 from "./cats-hard-01.json";
import p_cats_large_01 from "./cats-large-01.json";
import p_cats_medium_01 from "./cats-medium-01.json";
import p_cats_medium_02 from "./cats-medium-02.json";
import p_chemistry_easy_01 from "./chemistry-easy-01.json";
import p_chemistry_easy_02 from "./chemistry-easy-02.json";
import p_chemistry_hard_01 from "./chemistry-hard-01.json";
import p_chemistry_large_01 from "./chemistry-large-01.json";
import p_chemistry_medium_01 from "./chemistry-medium-01.json";
import p_chemistry_medium_02 from "./chemistry-medium-02.json";
import p_chess_easy_01 from "./chess-easy-01.json";
import p_chess_easy_02 from "./chess-easy-02.json";
import p_chess_hard_01 from "./chess-hard-01.json";
import p_chess_large_01 from "./chess-large-01.json";
import p_chess_medium_01 from "./chess-medium-01.json";
import p_chess_medium_02 from "./chess-medium-02.json";
import p_christmas_easy_01 from "./christmas-easy-01.json";
import p_christmas_easy_02 from "./christmas-easy-02.json";
import p_christmas_easy_03 from "./christmas-easy-03.json";
import p_christmas_hard_01 from "./christmas-hard-01.json";
import p_christmas_hard_02 from "./christmas-hard-02.json";
import p_christmas_hard_03 from "./christmas-hard-03.json";
import p_christmas_large_01 from "./christmas-large-01.json";
import p_christmas_large_02 from "./christmas-large-02.json";
import p_christmas_medium_01 from "./christmas-medium-01.json";
import p_christmas_medium_02 from "./christmas-medium-02.json";
import p_christmas_medium_03 from "./christmas-medium-03.json";
import p_cities_easy_01 from "./cities-easy-01.json";
import p_cities_easy_02 from "./cities-easy-02.json";
import p_cities_hard_01 from "./cities-hard-01.json";
import p_cities_large_01 from "./cities-large-01.json";
import p_cities_medium_01 from "./cities-medium-01.json";
import p_cities_medium_02 from "./cities-medium-02.json";
import p_classical_easy_01 from "./classical-easy-01.json";
import p_classical_easy_02 from "./classical-easy-02.json";
import p_classical_hard_01 from "./classical-hard-01.json";
import p_classical_large_01 from "./classical-large-01.json";
import p_classical_medium_01 from "./classical-medium-01.json";
import p_classical_medium_02 from "./classical-medium-02.json";
import p_coffee_tea_easy_01 from "./coffee-tea-easy-01.json";
import p_coffee_tea_easy_02 from "./coffee-tea-easy-02.json";
import p_coffee_tea_hard_01 from "./coffee-tea-hard-01.json";
import p_coffee_tea_large_01 from "./coffee-tea-large-01.json";
import p_coffee_tea_medium_01 from "./coffee-tea-medium-01.json";
import p_coffee_tea_medium_02 from "./coffee-tea-medium-02.json";
import p_colors_easy_01 from "./colors-easy-01.json";
import p_colors_easy_02 from "./colors-easy-02.json";
import p_colors_hard_01 from "./colors-hard-01.json";
import p_colors_large_01 from "./colors-large-01.json";
import p_colors_medium_01 from "./colors-medium-01.json";
import p_colors_medium_02 from "./colors-medium-02.json";
import p_continents_easy_01 from "./continents-easy-01.json";
import p_continents_easy_02 from "./continents-easy-02.json";
import p_continents_hard_01 from "./continents-hard-01.json";
import p_continents_large_01 from "./continents-large-01.json";
import p_continents_medium_01 from "./continents-medium-01.json";
import p_continents_medium_02 from "./continents-medium-02.json";
import p_cooking_easy_01 from "./cooking-easy-01.json";
import p_cooking_easy_02 from "./cooking-easy-02.json";
import p_cooking_hard_01 from "./cooking-hard-01.json";
import p_cooking_large_01 from "./cooking-large-01.json";
import p_cooking_medium_01 from "./cooking-medium-01.json";
import p_cooking_medium_02 from "./cooking-medium-02.json";
import p_countries_easy_01 from "./countries-easy-01.json";
import p_countries_easy_02 from "./countries-easy-02.json";
import p_countries_hard_01 from "./countries-hard-01.json";
import p_countries_large_01 from "./countries-large-01.json";
import p_countries_medium_01 from "./countries-medium-01.json";
import p_countries_medium_02 from "./countries-medium-02.json";
import p_cycling_easy_01 from "./cycling-easy-01.json";
import p_cycling_easy_02 from "./cycling-easy-02.json";
import p_cycling_hard_01 from "./cycling-hard-01.json";
import p_cycling_large_01 from "./cycling-large-01.json";
import p_cycling_medium_01 from "./cycling-medium-01.json";
import p_cycling_medium_02 from "./cycling-medium-02.json";
import p_deserts_easy_01 from "./deserts-easy-01.json";
import p_deserts_easy_02 from "./deserts-easy-02.json";
import p_deserts_hard_01 from "./deserts-hard-01.json";
import p_deserts_large_01 from "./deserts-large-01.json";
import p_deserts_medium_01 from "./deserts-medium-01.json";
import p_deserts_medium_02 from "./deserts-medium-02.json";
import p_desserts_easy_01 from "./desserts-easy-01.json";
import p_desserts_easy_02 from "./desserts-easy-02.json";
import p_desserts_hard_01 from "./desserts-hard-01.json";
import p_desserts_large_01 from "./desserts-large-01.json";
import p_desserts_medium_01 from "./desserts-medium-01.json";
import p_desserts_medium_02 from "./desserts-medium-02.json";
import p_dinosaurs_easy_01 from "./dinosaurs-easy-01.json";
import p_dinosaurs_easy_02 from "./dinosaurs-easy-02.json";
import p_dinosaurs_hard_01 from "./dinosaurs-hard-01.json";
import p_dinosaurs_large_01 from "./dinosaurs-large-01.json";
import p_dinosaurs_medium_01 from "./dinosaurs-medium-01.json";
import p_dinosaurs_medium_02 from "./dinosaurs-medium-02.json";
import p_dogs_easy_01 from "./dogs-easy-01.json";
import p_dogs_easy_02 from "./dogs-easy-02.json";
import p_dogs_hard_01 from "./dogs-hard-01.json";
import p_dogs_large_01 from "./dogs-large-01.json";
import p_dogs_medium_01 from "./dogs-medium-01.json";
import p_dogs_medium_02 from "./dogs-medium-02.json";
import p_easter_easy_01 from "./easter-easy-01.json";
import p_easter_easy_02 from "./easter-easy-02.json";
import p_easter_hard_01 from "./easter-hard-01.json";
import p_easter_large_01 from "./easter-large-01.json";
import p_easter_medium_01 from "./easter-medium-01.json";
import p_easter_medium_02 from "./easter-medium-02.json";
import p_emotions_easy_01 from "./emotions-easy-01.json";
import p_emotions_easy_02 from "./emotions-easy-02.json";
import p_emotions_hard_01 from "./emotions-hard-01.json";
import p_emotions_large_01 from "./emotions-large-01.json";
import p_emotions_medium_01 from "./emotions-medium-01.json";
import p_emotions_medium_02 from "./emotions-medium-02.json";
import p_fall_easy_01 from "./fall-easy-01.json";
import p_fall_easy_02 from "./fall-easy-02.json";
import p_fall_easy_03 from "./fall-easy-03.json";
import p_fall_hard_01 from "./fall-hard-01.json";
import p_fall_hard_02 from "./fall-hard-02.json";
import p_fall_hard_03 from "./fall-hard-03.json";
import p_fall_large_01 from "./fall-large-01.json";
import p_fall_large_02 from "./fall-large-02.json";
import p_fall_medium_01 from "./fall-medium-01.json";
import p_fall_medium_02 from "./fall-medium-02.json";
import p_fall_medium_03 from "./fall-medium-03.json";
import p_farm_animals_easy_01 from "./farm-animals-easy-01.json";
import p_farm_animals_easy_02 from "./farm-animals-easy-02.json";
import p_farm_animals_hard_01 from "./farm-animals-hard-01.json";
import p_farm_animals_large_01 from "./farm-animals-large-01.json";
import p_farm_animals_medium_01 from "./farm-animals-medium-01.json";
import p_farm_animals_medium_02 from "./farm-animals-medium-02.json";
import p_farming_easy_01 from "./farming-easy-01.json";
import p_farming_easy_02 from "./farming-easy-02.json";
import p_farming_hard_01 from "./farming-hard-01.json";
import p_farming_large_01 from "./farming-large-01.json";
import p_farming_medium_01 from "./farming-medium-01.json";
import p_farming_medium_02 from "./farming-medium-02.json";
import p_fathers_day_easy_01 from "./fathers-day-easy-01.json";
import p_fathers_day_easy_02 from "./fathers-day-easy-02.json";
import p_fathers_day_hard_01 from "./fathers-day-hard-01.json";
import p_fathers_day_large_01 from "./fathers-day-large-01.json";
import p_fathers_day_medium_01 from "./fathers-day-medium-01.json";
import p_fathers_day_medium_02 from "./fathers-day-medium-02.json";
import p_fishing_easy_01 from "./fishing-easy-01.json";
import p_fishing_easy_02 from "./fishing-easy-02.json";
import p_fishing_hard_01 from "./fishing-hard-01.json";
import p_fishing_large_01 from "./fishing-large-01.json";
import p_fishing_medium_01 from "./fishing-medium-01.json";
import p_fishing_medium_02 from "./fishing-medium-02.json";
import p_flowers_easy_01 from "./flowers-easy-01.json";
import p_flowers_easy_02 from "./flowers-easy-02.json";
import p_flowers_hard_01 from "./flowers-hard-01.json";
import p_flowers_large_01 from "./flowers-large-01.json";
import p_flowers_medium_01 from "./flowers-medium-01.json";
import p_flowers_medium_02 from "./flowers-medium-02.json";
import p_food_easy_01 from "./food-easy-01.json";
import p_food_easy_02 from "./food-easy-02.json";
import p_food_easy_03 from "./food-easy-03.json";
import p_food_hard_01 from "./food-hard-01.json";
import p_food_hard_02 from "./food-hard-02.json";
import p_food_large_01 from "./food-large-01.json";
import p_food_large_02 from "./food-large-02.json";
import p_food_medium_01 from "./food-medium-01.json";
import p_food_medium_02 from "./food-medium-02.json";
import p_food_medium_03 from "./food-medium-03.json";
import p_forests_easy_01 from "./forests-easy-01.json";
import p_forests_easy_02 from "./forests-easy-02.json";
import p_forests_hard_01 from "./forests-hard-01.json";
import p_forests_large_01 from "./forests-large-01.json";
import p_forests_medium_01 from "./forests-medium-01.json";
import p_forests_medium_02 from "./forests-medium-02.json";
import p_friendship_easy_01 from "./friendship-easy-01.json";
import p_friendship_easy_02 from "./friendship-easy-02.json";
import p_friendship_hard_01 from "./friendship-hard-01.json";
import p_friendship_large_01 from "./friendship-large-01.json";
import p_friendship_medium_01 from "./friendship-medium-01.json";
import p_friendship_medium_02 from "./friendship-medium-02.json";
import p_fruits_easy_01 from "./fruits-easy-01.json";
import p_fruits_easy_02 from "./fruits-easy-02.json";
import p_fruits_hard_01 from "./fruits-hard-01.json";
import p_fruits_large_01 from "./fruits-large-01.json";
import p_fruits_medium_01 from "./fruits-medium-01.json";
import p_fruits_medium_02 from "./fruits-medium-02.json";
import p_garden_easy_01 from "./garden-easy-01.json";
import p_garden_easy_02 from "./garden-easy-02.json";
import p_garden_easy_03 from "./garden-easy-03.json";
import p_garden_hard_01 from "./garden-hard-01.json";
import p_garden_hard_02 from "./garden-hard-02.json";
import p_garden_hard_03 from "./garden-hard-03.json";
import p_garden_large_01 from "./garden-large-01.json";
import p_garden_large_02 from "./garden-large-02.json";
import p_garden_medium_01 from "./garden-medium-01.json";
import p_garden_medium_02 from "./garden-medium-02.json";
import p_garden_medium_03 from "./garden-medium-03.json";
import p_geology_easy_01 from "./geology-easy-01.json";
import p_geology_easy_02 from "./geology-easy-02.json";
import p_geology_hard_01 from "./geology-hard-01.json";
import p_geology_large_01 from "./geology-large-01.json";
import p_geology_medium_01 from "./geology-medium-01.json";
import p_geology_medium_02 from "./geology-medium-02.json";
import p_golf_easy_01 from "./golf-easy-01.json";
import p_golf_easy_02 from "./golf-easy-02.json";
import p_golf_hard_01 from "./golf-hard-01.json";
import p_golf_large_01 from "./golf-large-01.json";
import p_golf_medium_01 from "./golf-medium-01.json";
import p_golf_medium_02 from "./golf-medium-02.json";
import p_gratitude_easy_01 from "./gratitude-easy-01.json";
import p_gratitude_easy_02 from "./gratitude-easy-02.json";
import p_gratitude_hard_01 from "./gratitude-hard-01.json";
import p_gratitude_large_01 from "./gratitude-large-01.json";
import p_gratitude_medium_01 from "./gratitude-medium-01.json";
import p_gratitude_medium_02 from "./gratitude-medium-02.json";
import p_halloween_easy_01 from "./halloween-easy-01.json";
import p_halloween_easy_02 from "./halloween-easy-02.json";
import p_halloween_easy_03 from "./halloween-easy-03.json";
import p_halloween_hard_01 from "./halloween-hard-01.json";
import p_halloween_hard_02 from "./halloween-hard-02.json";
import p_halloween_hard_03 from "./halloween-hard-03.json";
import p_halloween_large_01 from "./halloween-large-01.json";
import p_halloween_large_02 from "./halloween-large-02.json";
import p_halloween_medium_01 from "./halloween-medium-01.json";
import p_halloween_medium_02 from "./halloween-medium-02.json";
import p_halloween_medium_03 from "./halloween-medium-03.json";
import p_hard_pack_hard_01 from "./hard-pack-hard-01.json";
import p_hard_pack_hard_02 from "./hard-pack-hard-02.json";
import p_hard_pack_hard_03 from "./hard-pack-hard-03.json";
import p_herbs_easy_01 from "./herbs-easy-01.json";
import p_herbs_easy_02 from "./herbs-easy-02.json";
import p_herbs_hard_01 from "./herbs-hard-01.json";
import p_herbs_large_01 from "./herbs-large-01.json";
import p_herbs_medium_01 from "./herbs-medium-01.json";
import p_herbs_medium_02 from "./herbs-medium-02.json";
import p_hiking_easy_01 from "./hiking-easy-01.json";
import p_hiking_easy_02 from "./hiking-easy-02.json";
import p_hiking_hard_01 from "./hiking-hard-01.json";
import p_hiking_large_01 from "./hiking-large-01.json";
import p_hiking_medium_01 from "./hiking-medium-01.json";
import p_hiking_medium_02 from "./hiking-medium-02.json";
import p_home_easy_01 from "./home-easy-01.json";
import p_home_easy_02 from "./home-easy-02.json";
import p_home_hard_01 from "./home-hard-01.json";
import p_home_large_01 from "./home-large-01.json";
import p_home_medium_01 from "./home-medium-01.json";
import p_home_medium_02 from "./home-medium-02.json";
import p_horses_easy_01 from "./horses-easy-01.json";
import p_horses_easy_02 from "./horses-easy-02.json";
import p_horses_hard_01 from "./horses-hard-01.json";
import p_horses_large_01 from "./horses-large-01.json";
import p_horses_medium_01 from "./horses-medium-01.json";
import p_horses_medium_02 from "./horses-medium-02.json";
import p_human_body_easy_01 from "./human-body-easy-01.json";
import p_human_body_easy_02 from "./human-body-easy-02.json";
import p_human_body_hard_01 from "./human-body-hard-01.json";
import p_human_body_large_01 from "./human-body-large-01.json";
import p_human_body_medium_01 from "./human-body-medium-01.json";
import p_human_body_medium_02 from "./human-body-medium-02.json";
import p_independence_day_easy_01 from "./independence-day-easy-01.json";
import p_independence_day_easy_02 from "./independence-day-easy-02.json";
import p_independence_day_hard_01 from "./independence-day-hard-01.json";
import p_independence_day_large_01 from "./independence-day-large-01.json";
import p_independence_day_medium_01 from "./independence-day-medium-01.json";
import p_independence_day_medium_02 from "./independence-day-medium-02.json";
import p_insects_easy_01 from "./insects-easy-01.json";
import p_insects_easy_02 from "./insects-easy-02.json";
import p_insects_hard_01 from "./insects-hard-01.json";
import p_insects_large_01 from "./insects-large-01.json";
import p_insects_medium_01 from "./insects-medium-01.json";
import p_insects_medium_02 from "./insects-medium-02.json";
import p_instruments_easy_01 from "./instruments-easy-01.json";
import p_instruments_easy_02 from "./instruments-easy-02.json";
import p_instruments_hard_01 from "./instruments-hard-01.json";
import p_instruments_large_01 from "./instruments-large-01.json";
import p_instruments_medium_01 from "./instruments-medium-01.json";
import p_instruments_medium_02 from "./instruments-medium-02.json";
import p_islands_easy_01 from "./islands-easy-01.json";
import p_islands_easy_02 from "./islands-easy-02.json";
import p_islands_hard_01 from "./islands-hard-01.json";
import p_islands_large_01 from "./islands-large-01.json";
import p_islands_medium_01 from "./islands-medium-01.json";
import p_islands_medium_02 from "./islands-medium-02.json";
import p_jazz_easy_01 from "./jazz-easy-01.json";
import p_jazz_easy_02 from "./jazz-easy-02.json";
import p_jazz_hard_01 from "./jazz-hard-01.json";
import p_jazz_large_01 from "./jazz-large-01.json";
import p_jazz_medium_01 from "./jazz-medium-01.json";
import p_jazz_medium_02 from "./jazz-medium-02.json";
import p_jobs_easy_01 from "./jobs-easy-01.json";
import p_jobs_easy_02 from "./jobs-easy-02.json";
import p_jobs_hard_01 from "./jobs-hard-01.json";
import p_jobs_large_01 from "./jobs-large-01.json";
import p_jobs_medium_01 from "./jobs-medium-01.json";
import p_jobs_medium_02 from "./jobs-medium-02.json";
import p_kindness_easy_01 from "./kindness-easy-01.json";
import p_kindness_easy_02 from "./kindness-easy-02.json";
import p_kindness_hard_01 from "./kindness-hard-01.json";
import p_kindness_large_01 from "./kindness-large-01.json";
import p_kindness_medium_01 from "./kindness-medium-01.json";
import p_kindness_medium_02 from "./kindness-medium-02.json";
import p_kitchen_easy_01 from "./kitchen-easy-01.json";
import p_kitchen_easy_02 from "./kitchen-easy-02.json";
import p_kitchen_hard_01 from "./kitchen-hard-01.json";
import p_kitchen_large_01 from "./kitchen-large-01.json";
import p_kitchen_medium_01 from "./kitchen-medium-01.json";
import p_kitchen_medium_02 from "./kitchen-medium-02.json";
import p_knitting_easy_01 from "./knitting-easy-01.json";
import p_knitting_easy_02 from "./knitting-easy-02.json";
import p_knitting_hard_01 from "./knitting-hard-01.json";
import p_knitting_large_01 from "./knitting-large-01.json";
import p_knitting_medium_01 from "./knitting-medium-01.json";
import p_knitting_medium_02 from "./knitting-medium-02.json";
import p_lakes_easy_01 from "./lakes-easy-01.json";
import p_lakes_easy_02 from "./lakes-easy-02.json";
import p_lakes_hard_01 from "./lakes-hard-01.json";
import p_lakes_large_01 from "./lakes-large-01.json";
import p_lakes_medium_01 from "./lakes-medium-01.json";
import p_lakes_medium_02 from "./lakes-medium-02.json";
import p_landmarks_easy_01 from "./landmarks-easy-01.json";
import p_landmarks_easy_02 from "./landmarks-easy-02.json";
import p_landmarks_hard_01 from "./landmarks-hard-01.json";
import p_landmarks_large_01 from "./landmarks-large-01.json";
import p_landmarks_medium_01 from "./landmarks-medium-01.json";
import p_landmarks_medium_02 from "./landmarks-medium-02.json";
import p_large_print_pack_large_01 from "./large-print-pack-large-01.json";
import p_large_print_pack_large_02 from "./large-print-pack-large-02.json";
import p_large_print_pack_large_03 from "./large-print-pack-large-03.json";
import p_large_print_pack_large_04 from "./large-print-pack-large-04.json";
import p_large_print_pack_large_05 from "./large-print-pack-large-05.json";
import p_large_print_pack_large_06 from "./large-print-pack-large-06.json";
import p_large_print_pack_large_07 from "./large-print-pack-large-07.json";
import p_large_print_pack_large_08 from "./large-print-pack-large-08.json";
import p_large_print_pack_large_09 from "./large-print-pack-large-09.json";
import p_large_print_pack_large_10 from "./large-print-pack-large-10.json";
import p_large_print_pack_large_11 from "./large-print-pack-large-11.json";
import p_large_print_pack_large_12 from "./large-print-pack-large-12.json";
import p_mindfulness_easy_01 from "./mindfulness-easy-01.json";
import p_mindfulness_easy_02 from "./mindfulness-easy-02.json";
import p_mindfulness_hard_01 from "./mindfulness-hard-01.json";
import p_mindfulness_large_01 from "./mindfulness-large-01.json";
import p_mindfulness_medium_01 from "./mindfulness-medium-01.json";
import p_mindfulness_medium_02 from "./mindfulness-medium-02.json";
import p_money_easy_01 from "./money-easy-01.json";
import p_money_easy_02 from "./money-easy-02.json";
import p_money_hard_01 from "./money-hard-01.json";
import p_money_large_01 from "./money-large-01.json";
import p_money_medium_01 from "./money-medium-01.json";
import p_money_medium_02 from "./money-medium-02.json";
import p_mothers_day_easy_01 from "./mothers-day-easy-01.json";
import p_mothers_day_easy_02 from "./mothers-day-easy-02.json";
import p_mothers_day_hard_01 from "./mothers-day-hard-01.json";
import p_mothers_day_large_01 from "./mothers-day-large-01.json";
import p_mothers_day_medium_01 from "./mothers-day-medium-01.json";
import p_mothers_day_medium_02 from "./mothers-day-medium-02.json";
import p_mountains_easy_01 from "./mountains-easy-01.json";
import p_mountains_easy_02 from "./mountains-easy-02.json";
import p_mountains_hard_01 from "./mountains-hard-01.json";
import p_mountains_large_01 from "./mountains-large-01.json";
import p_mountains_medium_01 from "./mountains-medium-01.json";
import p_mountains_medium_02 from "./mountains-medium-02.json";
import p_museums_easy_01 from "./museums-easy-01.json";
import p_museums_easy_02 from "./museums-easy-02.json";
import p_museums_hard_01 from "./museums-hard-01.json";
import p_museums_large_01 from "./museums-large-01.json";
import p_museums_medium_01 from "./museums-medium-01.json";
import p_museums_medium_02 from "./museums-medium-02.json";
import p_music_easy_01 from "./music-easy-01.json";
import p_music_easy_02 from "./music-easy-02.json";
import p_music_hard_01 from "./music-hard-01.json";
import p_music_large_01 from "./music-large-01.json";
import p_music_medium_01 from "./music-medium-01.json";
import p_music_medium_02 from "./music-medium-02.json";
import p_music_terms_easy_01 from "./music-terms-easy-01.json";
import p_music_terms_easy_02 from "./music-terms-easy-02.json";
import p_music_terms_hard_01 from "./music-terms-hard-01.json";
import p_music_terms_large_01 from "./music-terms-large-01.json";
import p_music_terms_medium_01 from "./music-terms-medium-01.json";
import p_music_terms_medium_02 from "./music-terms-medium-02.json";
import p_mythology_easy_01 from "./mythology-easy-01.json";
import p_mythology_easy_02 from "./mythology-easy-02.json";
import p_mythology_hard_01 from "./mythology-hard-01.json";
import p_mythology_large_01 from "./mythology-large-01.json";
import p_mythology_medium_01 from "./mythology-medium-01.json";
import p_mythology_medium_02 from "./mythology-medium-02.json";
import p_national_parks_easy_01 from "./national-parks-easy-01.json";
import p_national_parks_easy_02 from "./national-parks-easy-02.json";
import p_national_parks_hard_01 from "./national-parks-hard-01.json";
import p_national_parks_large_01 from "./national-parks-large-01.json";
import p_national_parks_medium_01 from "./national-parks-medium-01.json";
import p_national_parks_medium_02 from "./national-parks-medium-02.json";
import p_new_year_easy_01 from "./new-year-easy-01.json";
import p_new_year_easy_02 from "./new-year-easy-02.json";
import p_new_year_hard_01 from "./new-year-hard-01.json";
import p_new_year_large_01 from "./new-year-large-01.json";
import p_new_year_medium_01 from "./new-year-medium-01.json";
import p_new_year_medium_02 from "./new-year-medium-02.json";
import p_ocean_easy_01 from "./ocean-easy-01.json";
import p_ocean_easy_02 from "./ocean-easy-02.json";
import p_ocean_easy_03 from "./ocean-easy-03.json";
import p_ocean_hard_01 from "./ocean-hard-01.json";
import p_ocean_hard_02 from "./ocean-hard-02.json";
import p_ocean_hard_03 from "./ocean-hard-03.json";
import p_ocean_large_01 from "./ocean-large-01.json";
import p_ocean_large_02 from "./ocean-large-02.json";
import p_ocean_medium_01 from "./ocean-medium-01.json";
import p_ocean_medium_02 from "./ocean-medium-02.json";
import p_ocean_medium_03 from "./ocean-medium-03.json";
import p_painting_easy_01 from "./painting-easy-01.json";
import p_painting_easy_02 from "./painting-easy-02.json";
import p_painting_hard_01 from "./painting-hard-01.json";
import p_painting_large_01 from "./painting-large-01.json";
import p_painting_medium_01 from "./painting-medium-01.json";
import p_painting_medium_02 from "./painting-medium-02.json";
import p_photography_easy_01 from "./photography-easy-01.json";
import p_photography_easy_02 from "./photography-easy-02.json";
import p_photography_hard_01 from "./photography-hard-01.json";
import p_photography_large_01 from "./photography-large-01.json";
import p_photography_medium_01 from "./photography-medium-01.json";
import p_photography_medium_02 from "./photography-medium-02.json";
import p_presidents_easy_01 from "./presidents-easy-01.json";
import p_presidents_easy_02 from "./presidents-easy-02.json";
import p_presidents_hard_01 from "./presidents-hard-01.json";
import p_presidents_large_01 from "./presidents-large-01.json";
import p_presidents_medium_01 from "./presidents-medium-01.json";
import p_presidents_medium_02 from "./presidents-medium-02.json";
import p_quilting_easy_01 from "./quilting-easy-01.json";
import p_quilting_easy_02 from "./quilting-easy-02.json";
import p_quilting_hard_01 from "./quilting-hard-01.json";
import p_quilting_large_01 from "./quilting-large-01.json";
import p_quilting_medium_01 from "./quilting-medium-01.json";
import p_quilting_medium_02 from "./quilting-medium-02.json";
import p_reading_easy_01 from "./reading-easy-01.json";
import p_reading_easy_02 from "./reading-easy-02.json";
import p_reading_hard_01 from "./reading-hard-01.json";
import p_reading_large_01 from "./reading-large-01.json";
import p_reading_medium_01 from "./reading-medium-01.json";
import p_reading_medium_02 from "./reading-medium-02.json";
import p_reptiles_easy_01 from "./reptiles-easy-01.json";
import p_reptiles_easy_02 from "./reptiles-easy-02.json";
import p_reptiles_hard_01 from "./reptiles-hard-01.json";
import p_reptiles_large_01 from "./reptiles-large-01.json";
import p_reptiles_medium_01 from "./reptiles-medium-01.json";
import p_reptiles_medium_02 from "./reptiles-medium-02.json";
import p_rivers_easy_01 from "./rivers-easy-01.json";
import p_rivers_easy_02 from "./rivers-easy-02.json";
import p_rivers_hard_01 from "./rivers-hard-01.json";
import p_rivers_large_01 from "./rivers-large-01.json";
import p_rivers_medium_01 from "./rivers-medium-01.json";
import p_rivers_medium_02 from "./rivers-medium-02.json";
import p_school_easy_01 from "./school-easy-01.json";
import p_school_easy_02 from "./school-easy-02.json";
import p_school_hard_01 from "./school-hard-01.json";
import p_school_large_01 from "./school-large-01.json";
import p_school_medium_01 from "./school-medium-01.json";
import p_school_medium_02 from "./school-medium-02.json";
import p_sewing_easy_01 from "./sewing-easy-01.json";
import p_sewing_easy_02 from "./sewing-easy-02.json";
import p_sewing_hard_01 from "./sewing-hard-01.json";
import p_sewing_large_01 from "./sewing-large-01.json";
import p_sewing_medium_01 from "./sewing-medium-01.json";
import p_sewing_medium_02 from "./sewing-medium-02.json";
import p_shopping_easy_01 from "./shopping-easy-01.json";
import p_shopping_easy_02 from "./shopping-easy-02.json";
import p_shopping_hard_01 from "./shopping-hard-01.json";
import p_shopping_large_01 from "./shopping-large-01.json";
import p_shopping_medium_01 from "./shopping-medium-01.json";
import p_shopping_medium_02 from "./shopping-medium-02.json";
import p_soccer_easy_01 from "./soccer-easy-01.json";
import p_soccer_easy_02 from "./soccer-easy-02.json";
import p_soccer_hard_01 from "./soccer-hard-01.json";
import p_soccer_large_01 from "./soccer-large-01.json";
import p_soccer_medium_01 from "./soccer-medium-01.json";
import p_soccer_medium_02 from "./soccer-medium-02.json";
import p_space_easy_01 from "./space-easy-01.json";
import p_space_easy_02 from "./space-easy-02.json";
import p_space_hard_01 from "./space-hard-01.json";
import p_space_large_01 from "./space-large-01.json";
import p_space_medium_01 from "./space-medium-01.json";
import p_space_medium_02 from "./space-medium-02.json";
import p_sports_easy_01 from "./sports-easy-01.json";
import p_sports_easy_02 from "./sports-easy-02.json";
import p_sports_easy_03 from "./sports-easy-03.json";
import p_sports_hard_01 from "./sports-hard-01.json";
import p_sports_hard_02 from "./sports-hard-02.json";
import p_sports_large_01 from "./sports-large-01.json";
import p_sports_large_02 from "./sports-large-02.json";
import p_sports_medium_01 from "./sports-medium-01.json";
import p_sports_medium_02 from "./sports-medium-02.json";
import p_sports_medium_03 from "./sports-medium-03.json";
import p_spring_easy_01 from "./spring-easy-01.json";
import p_spring_easy_02 from "./spring-easy-02.json";
import p_spring_hard_01 from "./spring-hard-01.json";
import p_spring_large_01 from "./spring-large-01.json";
import p_spring_medium_01 from "./spring-medium-01.json";
import p_spring_medium_02 from "./spring-medium-02.json";
import p_st_patricks_easy_01 from "./st-patricks-easy-01.json";
import p_st_patricks_easy_02 from "./st-patricks-easy-02.json";
import p_st_patricks_hard_01 from "./st-patricks-hard-01.json";
import p_st_patricks_large_01 from "./st-patricks-large-01.json";
import p_st_patricks_medium_01 from "./st-patricks-medium-01.json";
import p_st_patricks_medium_02 from "./st-patricks-medium-02.json";
import p_summer_easy_01 from "./summer-easy-01.json";
import p_summer_easy_02 from "./summer-easy-02.json";
import p_summer_hard_01 from "./summer-hard-01.json";
import p_summer_large_01 from "./summer-large-01.json";
import p_summer_medium_01 from "./summer-medium-01.json";
import p_summer_medium_02 from "./summer-medium-02.json";
import p_swimming_easy_01 from "./swimming-easy-01.json";
import p_swimming_easy_02 from "./swimming-easy-02.json";
import p_swimming_hard_01 from "./swimming-hard-01.json";
import p_swimming_large_01 from "./swimming-large-01.json";
import p_swimming_medium_01 from "./swimming-medium-01.json";
import p_swimming_medium_02 from "./swimming-medium-02.json";
import p_tennis_easy_01 from "./tennis-easy-01.json";
import p_tennis_easy_02 from "./tennis-easy-02.json";
import p_tennis_hard_01 from "./tennis-hard-01.json";
import p_tennis_large_01 from "./tennis-large-01.json";
import p_tennis_medium_01 from "./tennis-medium-01.json";
import p_tennis_medium_02 from "./tennis-medium-02.json";
import p_thanksgiving_easy_01 from "./thanksgiving-easy-01.json";
import p_thanksgiving_easy_02 from "./thanksgiving-easy-02.json";
import p_thanksgiving_easy_03 from "./thanksgiving-easy-03.json";
import p_thanksgiving_hard_01 from "./thanksgiving-hard-01.json";
import p_thanksgiving_hard_02 from "./thanksgiving-hard-02.json";
import p_thanksgiving_large_01 from "./thanksgiving-large-01.json";
import p_thanksgiving_large_02 from "./thanksgiving-large-02.json";
import p_thanksgiving_medium_01 from "./thanksgiving-medium-01.json";
import p_thanksgiving_medium_02 from "./thanksgiving-medium-02.json";
import p_thanksgiving_medium_03 from "./thanksgiving-medium-03.json";
import p_tools_easy_01 from "./tools-easy-01.json";
import p_tools_easy_02 from "./tools-easy-02.json";
import p_tools_hard_01 from "./tools-hard-01.json";
import p_tools_large_01 from "./tools-large-01.json";
import p_tools_medium_01 from "./tools-medium-01.json";
import p_tools_medium_02 from "./tools-medium-02.json";
import p_trains_easy_01 from "./trains-easy-01.json";
import p_trains_easy_02 from "./trains-easy-02.json";
import p_trains_hard_01 from "./trains-hard-01.json";
import p_trains_large_01 from "./trains-large-01.json";
import p_trains_medium_01 from "./trains-medium-01.json";
import p_trains_medium_02 from "./trains-medium-02.json";
import p_travel_easy_01 from "./travel-easy-01.json";
import p_travel_easy_02 from "./travel-easy-02.json";
import p_travel_hard_01 from "./travel-hard-01.json";
import p_travel_large_01 from "./travel-large-01.json";
import p_travel_medium_01 from "./travel-medium-01.json";
import p_travel_medium_02 from "./travel-medium-02.json";
import p_trees_easy_01 from "./trees-easy-01.json";
import p_trees_easy_02 from "./trees-easy-02.json";
import p_trees_hard_01 from "./trees-hard-01.json";
import p_trees_large_01 from "./trees-large-01.json";
import p_trees_medium_01 from "./trees-medium-01.json";
import p_trees_medium_02 from "./trees-medium-02.json";
import p_us_states_easy_01 from "./us-states-easy-01.json";
import p_us_states_easy_02 from "./us-states-easy-02.json";
import p_us_states_hard_01 from "./us-states-hard-01.json";
import p_us_states_large_01 from "./us-states-large-01.json";
import p_us_states_medium_01 from "./us-states-medium-01.json";
import p_us_states_medium_02 from "./us-states-medium-02.json";
import p_valentines_easy_01 from "./valentines-easy-01.json";
import p_valentines_easy_02 from "./valentines-easy-02.json";
import p_valentines_hard_01 from "./valentines-hard-01.json";
import p_valentines_large_01 from "./valentines-large-01.json";
import p_valentines_medium_01 from "./valentines-medium-01.json";
import p_valentines_medium_02 from "./valentines-medium-02.json";
import p_vegetables_easy_01 from "./vegetables-easy-01.json";
import p_vegetables_easy_02 from "./vegetables-easy-02.json";
import p_vegetables_hard_01 from "./vegetables-hard-01.json";
import p_vegetables_large_01 from "./vegetables-large-01.json";
import p_vegetables_medium_01 from "./vegetables-medium-01.json";
import p_vegetables_medium_02 from "./vegetables-medium-02.json";
import p_volcanoes_easy_01 from "./volcanoes-easy-01.json";
import p_volcanoes_easy_02 from "./volcanoes-easy-02.json";
import p_volcanoes_hard_01 from "./volcanoes-hard-01.json";
import p_volcanoes_large_01 from "./volcanoes-large-01.json";
import p_volcanoes_medium_01 from "./volcanoes-medium-01.json";
import p_volcanoes_medium_02 from "./volcanoes-medium-02.json";
import p_weather_easy_01 from "./weather-easy-01.json";
import p_weather_easy_02 from "./weather-easy-02.json";
import p_weather_hard_01 from "./weather-hard-01.json";
import p_weather_large_01 from "./weather-large-01.json";
import p_weather_medium_01 from "./weather-medium-01.json";
import p_weather_medium_02 from "./weather-medium-02.json";
import p_wedding_easy_01 from "./wedding-easy-01.json";
import p_wedding_easy_02 from "./wedding-easy-02.json";
import p_wedding_hard_01 from "./wedding-hard-01.json";
import p_wedding_large_01 from "./wedding-large-01.json";
import p_wedding_medium_01 from "./wedding-medium-01.json";
import p_wedding_medium_02 from "./wedding-medium-02.json";
import p_winter_easy_01 from "./winter-easy-01.json";
import p_winter_easy_02 from "./winter-easy-02.json";
import p_winter_easy_03 from "./winter-easy-03.json";
import p_winter_hard_01 from "./winter-hard-01.json";
import p_winter_hard_02 from "./winter-hard-02.json";
import p_winter_large_01 from "./winter-large-01.json";
import p_winter_large_02 from "./winter-large-02.json";
import p_winter_medium_01 from "./winter-medium-01.json";
import p_winter_medium_02 from "./winter-medium-02.json";
import p_winter_medium_03 from "./winter-medium-03.json";
import p_world_capitals_easy_01 from "./world-capitals-easy-01.json";
import p_world_capitals_easy_02 from "./world-capitals-easy-02.json";
import p_world_capitals_hard_01 from "./world-capitals-hard-01.json";
import p_world_capitals_large_01 from "./world-capitals-large-01.json";
import p_world_capitals_medium_01 from "./world-capitals-medium-01.json";
import p_world_capitals_medium_02 from "./world-capitals-medium-02.json";
import p_yoga_easy_01 from "./yoga-easy-01.json";
import p_yoga_easy_02 from "./yoga-easy-02.json";
import p_yoga_hard_01 from "./yoga-hard-01.json";
import p_yoga_large_01 from "./yoga-large-01.json";
import p_yoga_medium_01 from "./yoga-medium-01.json";
import p_yoga_medium_02 from "./yoga-medium-02.json";

export const puzzles = [
  p_airplanes_easy_01,
  p_airplanes_easy_02,
  p_airplanes_hard_01,
  p_airplanes_large_01,
  p_airplanes_medium_01,
  p_airplanes_medium_02,
  p_american_history_easy_01,
  p_american_history_easy_02,
  p_american_history_hard_01,
  p_american_history_large_01,
  p_american_history_medium_01,
  p_american_history_medium_02,
  p_animals_easy_01,
  p_animals_easy_02,
  p_animals_easy_03,
  p_animals_hard_01,
  p_animals_hard_02,
  p_animals_hard_03,
  p_animals_large_01,
  p_animals_large_02,
  p_animals_medium_01,
  p_animals_medium_02,
  p_animals_medium_03,
  p_architecture_easy_01,
  p_architecture_easy_02,
  p_architecture_hard_01,
  p_architecture_large_01,
  p_architecture_medium_01,
  p_architecture_medium_02,
  p_astronomy_easy_01,
  p_astronomy_easy_02,
  p_astronomy_hard_01,
  p_astronomy_large_01,
  p_astronomy_medium_01,
  p_astronomy_medium_02,
  p_baking_easy_01,
  p_baking_easy_02,
  p_baking_hard_01,
  p_baking_large_01,
  p_baking_medium_01,
  p_baking_medium_02,
  p_baseball_easy_01,
  p_baseball_easy_02,
  p_baseball_hard_01,
  p_baseball_large_01,
  p_baseball_medium_01,
  p_baseball_medium_02,
  p_basketball_easy_01,
  p_basketball_easy_02,
  p_basketball_hard_01,
  p_basketball_large_01,
  p_basketball_medium_01,
  p_basketball_medium_02,
  p_beach_easy_01,
  p_beach_easy_02,
  p_beach_hard_01,
  p_beach_large_01,
  p_beach_medium_01,
  p_beach_medium_02,
  p_bible_easy_01,
  p_bible_easy_02,
  p_bible_easy_03,
  p_bible_easy_04,
  p_bible_hard_01,
  p_bible_hard_02,
  p_bible_hard_03,
  p_bible_large_01,
  p_bible_large_02,
  p_bible_medium_01,
  p_bible_medium_02,
  p_bible_medium_03,
  p_bible_medium_04,
  p_birds_easy_01,
  p_birds_easy_02,
  p_birds_hard_01,
  p_birds_large_01,
  p_birds_medium_01,
  p_birds_medium_02,
  p_birthday_easy_01,
  p_birthday_easy_02,
  p_birthday_hard_01,
  p_birthday_large_01,
  p_birthday_medium_01,
  p_birthday_medium_02,
  p_board_games_easy_01,
  p_board_games_easy_02,
  p_board_games_hard_01,
  p_board_games_large_01,
  p_board_games_medium_01,
  p_board_games_medium_02,
  p_breakfast_easy_01,
  p_breakfast_easy_02,
  p_breakfast_hard_01,
  p_breakfast_large_01,
  p_breakfast_medium_01,
  p_breakfast_medium_02,
  p_camping_easy_01,
  p_camping_easy_02,
  p_camping_hard_01,
  p_camping_large_01,
  p_camping_medium_01,
  p_camping_medium_02,
  p_cars_easy_01,
  p_cars_easy_02,
  p_cars_hard_01,
  p_cars_large_01,
  p_cars_medium_01,
  p_cars_medium_02,
  p_cats_easy_01,
  p_cats_easy_02,
  p_cats_hard_01,
  p_cats_large_01,
  p_cats_medium_01,
  p_cats_medium_02,
  p_chemistry_easy_01,
  p_chemistry_easy_02,
  p_chemistry_hard_01,
  p_chemistry_large_01,
  p_chemistry_medium_01,
  p_chemistry_medium_02,
  p_chess_easy_01,
  p_chess_easy_02,
  p_chess_hard_01,
  p_chess_large_01,
  p_chess_medium_01,
  p_chess_medium_02,
  p_christmas_easy_01,
  p_christmas_easy_02,
  p_christmas_easy_03,
  p_christmas_hard_01,
  p_christmas_hard_02,
  p_christmas_hard_03,
  p_christmas_large_01,
  p_christmas_large_02,
  p_christmas_medium_01,
  p_christmas_medium_02,
  p_christmas_medium_03,
  p_cities_easy_01,
  p_cities_easy_02,
  p_cities_hard_01,
  p_cities_large_01,
  p_cities_medium_01,
  p_cities_medium_02,
  p_classical_easy_01,
  p_classical_easy_02,
  p_classical_hard_01,
  p_classical_large_01,
  p_classical_medium_01,
  p_classical_medium_02,
  p_coffee_tea_easy_01,
  p_coffee_tea_easy_02,
  p_coffee_tea_hard_01,
  p_coffee_tea_large_01,
  p_coffee_tea_medium_01,
  p_coffee_tea_medium_02,
  p_colors_easy_01,
  p_colors_easy_02,
  p_colors_hard_01,
  p_colors_large_01,
  p_colors_medium_01,
  p_colors_medium_02,
  p_continents_easy_01,
  p_continents_easy_02,
  p_continents_hard_01,
  p_continents_large_01,
  p_continents_medium_01,
  p_continents_medium_02,
  p_cooking_easy_01,
  p_cooking_easy_02,
  p_cooking_hard_01,
  p_cooking_large_01,
  p_cooking_medium_01,
  p_cooking_medium_02,
  p_countries_easy_01,
  p_countries_easy_02,
  p_countries_hard_01,
  p_countries_large_01,
  p_countries_medium_01,
  p_countries_medium_02,
  p_cycling_easy_01,
  p_cycling_easy_02,
  p_cycling_hard_01,
  p_cycling_large_01,
  p_cycling_medium_01,
  p_cycling_medium_02,
  p_deserts_easy_01,
  p_deserts_easy_02,
  p_deserts_hard_01,
  p_deserts_large_01,
  p_deserts_medium_01,
  p_deserts_medium_02,
  p_desserts_easy_01,
  p_desserts_easy_02,
  p_desserts_hard_01,
  p_desserts_large_01,
  p_desserts_medium_01,
  p_desserts_medium_02,
  p_dinosaurs_easy_01,
  p_dinosaurs_easy_02,
  p_dinosaurs_hard_01,
  p_dinosaurs_large_01,
  p_dinosaurs_medium_01,
  p_dinosaurs_medium_02,
  p_dogs_easy_01,
  p_dogs_easy_02,
  p_dogs_hard_01,
  p_dogs_large_01,
  p_dogs_medium_01,
  p_dogs_medium_02,
  p_easter_easy_01,
  p_easter_easy_02,
  p_easter_hard_01,
  p_easter_large_01,
  p_easter_medium_01,
  p_easter_medium_02,
  p_emotions_easy_01,
  p_emotions_easy_02,
  p_emotions_hard_01,
  p_emotions_large_01,
  p_emotions_medium_01,
  p_emotions_medium_02,
  p_fall_easy_01,
  p_fall_easy_02,
  p_fall_easy_03,
  p_fall_hard_01,
  p_fall_hard_02,
  p_fall_hard_03,
  p_fall_large_01,
  p_fall_large_02,
  p_fall_medium_01,
  p_fall_medium_02,
  p_fall_medium_03,
  p_farm_animals_easy_01,
  p_farm_animals_easy_02,
  p_farm_animals_hard_01,
  p_farm_animals_large_01,
  p_farm_animals_medium_01,
  p_farm_animals_medium_02,
  p_farming_easy_01,
  p_farming_easy_02,
  p_farming_hard_01,
  p_farming_large_01,
  p_farming_medium_01,
  p_farming_medium_02,
  p_fathers_day_easy_01,
  p_fathers_day_easy_02,
  p_fathers_day_hard_01,
  p_fathers_day_large_01,
  p_fathers_day_medium_01,
  p_fathers_day_medium_02,
  p_fishing_easy_01,
  p_fishing_easy_02,
  p_fishing_hard_01,
  p_fishing_large_01,
  p_fishing_medium_01,
  p_fishing_medium_02,
  p_flowers_easy_01,
  p_flowers_easy_02,
  p_flowers_hard_01,
  p_flowers_large_01,
  p_flowers_medium_01,
  p_flowers_medium_02,
  p_food_easy_01,
  p_food_easy_02,
  p_food_easy_03,
  p_food_hard_01,
  p_food_hard_02,
  p_food_large_01,
  p_food_large_02,
  p_food_medium_01,
  p_food_medium_02,
  p_food_medium_03,
  p_forests_easy_01,
  p_forests_easy_02,
  p_forests_hard_01,
  p_forests_large_01,
  p_forests_medium_01,
  p_forests_medium_02,
  p_friendship_easy_01,
  p_friendship_easy_02,
  p_friendship_hard_01,
  p_friendship_large_01,
  p_friendship_medium_01,
  p_friendship_medium_02,
  p_fruits_easy_01,
  p_fruits_easy_02,
  p_fruits_hard_01,
  p_fruits_large_01,
  p_fruits_medium_01,
  p_fruits_medium_02,
  p_garden_easy_01,
  p_garden_easy_02,
  p_garden_easy_03,
  p_garden_hard_01,
  p_garden_hard_02,
  p_garden_hard_03,
  p_garden_large_01,
  p_garden_large_02,
  p_garden_medium_01,
  p_garden_medium_02,
  p_garden_medium_03,
  p_geology_easy_01,
  p_geology_easy_02,
  p_geology_hard_01,
  p_geology_large_01,
  p_geology_medium_01,
  p_geology_medium_02,
  p_golf_easy_01,
  p_golf_easy_02,
  p_golf_hard_01,
  p_golf_large_01,
  p_golf_medium_01,
  p_golf_medium_02,
  p_gratitude_easy_01,
  p_gratitude_easy_02,
  p_gratitude_hard_01,
  p_gratitude_large_01,
  p_gratitude_medium_01,
  p_gratitude_medium_02,
  p_halloween_easy_01,
  p_halloween_easy_02,
  p_halloween_easy_03,
  p_halloween_hard_01,
  p_halloween_hard_02,
  p_halloween_hard_03,
  p_halloween_large_01,
  p_halloween_large_02,
  p_halloween_medium_01,
  p_halloween_medium_02,
  p_halloween_medium_03,
  p_hard_pack_hard_01,
  p_hard_pack_hard_02,
  p_hard_pack_hard_03,
  p_herbs_easy_01,
  p_herbs_easy_02,
  p_herbs_hard_01,
  p_herbs_large_01,
  p_herbs_medium_01,
  p_herbs_medium_02,
  p_hiking_easy_01,
  p_hiking_easy_02,
  p_hiking_hard_01,
  p_hiking_large_01,
  p_hiking_medium_01,
  p_hiking_medium_02,
  p_home_easy_01,
  p_home_easy_02,
  p_home_hard_01,
  p_home_large_01,
  p_home_medium_01,
  p_home_medium_02,
  p_horses_easy_01,
  p_horses_easy_02,
  p_horses_hard_01,
  p_horses_large_01,
  p_horses_medium_01,
  p_horses_medium_02,
  p_human_body_easy_01,
  p_human_body_easy_02,
  p_human_body_hard_01,
  p_human_body_large_01,
  p_human_body_medium_01,
  p_human_body_medium_02,
  p_independence_day_easy_01,
  p_independence_day_easy_02,
  p_independence_day_hard_01,
  p_independence_day_large_01,
  p_independence_day_medium_01,
  p_independence_day_medium_02,
  p_insects_easy_01,
  p_insects_easy_02,
  p_insects_hard_01,
  p_insects_large_01,
  p_insects_medium_01,
  p_insects_medium_02,
  p_instruments_easy_01,
  p_instruments_easy_02,
  p_instruments_hard_01,
  p_instruments_large_01,
  p_instruments_medium_01,
  p_instruments_medium_02,
  p_islands_easy_01,
  p_islands_easy_02,
  p_islands_hard_01,
  p_islands_large_01,
  p_islands_medium_01,
  p_islands_medium_02,
  p_jazz_easy_01,
  p_jazz_easy_02,
  p_jazz_hard_01,
  p_jazz_large_01,
  p_jazz_medium_01,
  p_jazz_medium_02,
  p_jobs_easy_01,
  p_jobs_easy_02,
  p_jobs_hard_01,
  p_jobs_large_01,
  p_jobs_medium_01,
  p_jobs_medium_02,
  p_kindness_easy_01,
  p_kindness_easy_02,
  p_kindness_hard_01,
  p_kindness_large_01,
  p_kindness_medium_01,
  p_kindness_medium_02,
  p_kitchen_easy_01,
  p_kitchen_easy_02,
  p_kitchen_hard_01,
  p_kitchen_large_01,
  p_kitchen_medium_01,
  p_kitchen_medium_02,
  p_knitting_easy_01,
  p_knitting_easy_02,
  p_knitting_hard_01,
  p_knitting_large_01,
  p_knitting_medium_01,
  p_knitting_medium_02,
  p_lakes_easy_01,
  p_lakes_easy_02,
  p_lakes_hard_01,
  p_lakes_large_01,
  p_lakes_medium_01,
  p_lakes_medium_02,
  p_landmarks_easy_01,
  p_landmarks_easy_02,
  p_landmarks_hard_01,
  p_landmarks_large_01,
  p_landmarks_medium_01,
  p_landmarks_medium_02,
  p_large_print_pack_large_01,
  p_large_print_pack_large_02,
  p_large_print_pack_large_03,
  p_large_print_pack_large_04,
  p_large_print_pack_large_05,
  p_large_print_pack_large_06,
  p_large_print_pack_large_07,
  p_large_print_pack_large_08,
  p_large_print_pack_large_09,
  p_large_print_pack_large_10,
  p_large_print_pack_large_11,
  p_large_print_pack_large_12,
  p_mindfulness_easy_01,
  p_mindfulness_easy_02,
  p_mindfulness_hard_01,
  p_mindfulness_large_01,
  p_mindfulness_medium_01,
  p_mindfulness_medium_02,
  p_money_easy_01,
  p_money_easy_02,
  p_money_hard_01,
  p_money_large_01,
  p_money_medium_01,
  p_money_medium_02,
  p_mothers_day_easy_01,
  p_mothers_day_easy_02,
  p_mothers_day_hard_01,
  p_mothers_day_large_01,
  p_mothers_day_medium_01,
  p_mothers_day_medium_02,
  p_mountains_easy_01,
  p_mountains_easy_02,
  p_mountains_hard_01,
  p_mountains_large_01,
  p_mountains_medium_01,
  p_mountains_medium_02,
  p_museums_easy_01,
  p_museums_easy_02,
  p_museums_hard_01,
  p_museums_large_01,
  p_museums_medium_01,
  p_museums_medium_02,
  p_music_easy_01,
  p_music_easy_02,
  p_music_hard_01,
  p_music_large_01,
  p_music_medium_01,
  p_music_medium_02,
  p_music_terms_easy_01,
  p_music_terms_easy_02,
  p_music_terms_hard_01,
  p_music_terms_large_01,
  p_music_terms_medium_01,
  p_music_terms_medium_02,
  p_mythology_easy_01,
  p_mythology_easy_02,
  p_mythology_hard_01,
  p_mythology_large_01,
  p_mythology_medium_01,
  p_mythology_medium_02,
  p_national_parks_easy_01,
  p_national_parks_easy_02,
  p_national_parks_hard_01,
  p_national_parks_large_01,
  p_national_parks_medium_01,
  p_national_parks_medium_02,
  p_new_year_easy_01,
  p_new_year_easy_02,
  p_new_year_hard_01,
  p_new_year_large_01,
  p_new_year_medium_01,
  p_new_year_medium_02,
  p_ocean_easy_01,
  p_ocean_easy_02,
  p_ocean_easy_03,
  p_ocean_hard_01,
  p_ocean_hard_02,
  p_ocean_hard_03,
  p_ocean_large_01,
  p_ocean_large_02,
  p_ocean_medium_01,
  p_ocean_medium_02,
  p_ocean_medium_03,
  p_painting_easy_01,
  p_painting_easy_02,
  p_painting_hard_01,
  p_painting_large_01,
  p_painting_medium_01,
  p_painting_medium_02,
  p_photography_easy_01,
  p_photography_easy_02,
  p_photography_hard_01,
  p_photography_large_01,
  p_photography_medium_01,
  p_photography_medium_02,
  p_presidents_easy_01,
  p_presidents_easy_02,
  p_presidents_hard_01,
  p_presidents_large_01,
  p_presidents_medium_01,
  p_presidents_medium_02,
  p_quilting_easy_01,
  p_quilting_easy_02,
  p_quilting_hard_01,
  p_quilting_large_01,
  p_quilting_medium_01,
  p_quilting_medium_02,
  p_reading_easy_01,
  p_reading_easy_02,
  p_reading_hard_01,
  p_reading_large_01,
  p_reading_medium_01,
  p_reading_medium_02,
  p_reptiles_easy_01,
  p_reptiles_easy_02,
  p_reptiles_hard_01,
  p_reptiles_large_01,
  p_reptiles_medium_01,
  p_reptiles_medium_02,
  p_rivers_easy_01,
  p_rivers_easy_02,
  p_rivers_hard_01,
  p_rivers_large_01,
  p_rivers_medium_01,
  p_rivers_medium_02,
  p_school_easy_01,
  p_school_easy_02,
  p_school_hard_01,
  p_school_large_01,
  p_school_medium_01,
  p_school_medium_02,
  p_sewing_easy_01,
  p_sewing_easy_02,
  p_sewing_hard_01,
  p_sewing_large_01,
  p_sewing_medium_01,
  p_sewing_medium_02,
  p_shopping_easy_01,
  p_shopping_easy_02,
  p_shopping_hard_01,
  p_shopping_large_01,
  p_shopping_medium_01,
  p_shopping_medium_02,
  p_soccer_easy_01,
  p_soccer_easy_02,
  p_soccer_hard_01,
  p_soccer_large_01,
  p_soccer_medium_01,
  p_soccer_medium_02,
  p_space_easy_01,
  p_space_easy_02,
  p_space_hard_01,
  p_space_large_01,
  p_space_medium_01,
  p_space_medium_02,
  p_sports_easy_01,
  p_sports_easy_02,
  p_sports_easy_03,
  p_sports_hard_01,
  p_sports_hard_02,
  p_sports_large_01,
  p_sports_large_02,
  p_sports_medium_01,
  p_sports_medium_02,
  p_sports_medium_03,
  p_spring_easy_01,
  p_spring_easy_02,
  p_spring_hard_01,
  p_spring_large_01,
  p_spring_medium_01,
  p_spring_medium_02,
  p_st_patricks_easy_01,
  p_st_patricks_easy_02,
  p_st_patricks_hard_01,
  p_st_patricks_large_01,
  p_st_patricks_medium_01,
  p_st_patricks_medium_02,
  p_summer_easy_01,
  p_summer_easy_02,
  p_summer_hard_01,
  p_summer_large_01,
  p_summer_medium_01,
  p_summer_medium_02,
  p_swimming_easy_01,
  p_swimming_easy_02,
  p_swimming_hard_01,
  p_swimming_large_01,
  p_swimming_medium_01,
  p_swimming_medium_02,
  p_tennis_easy_01,
  p_tennis_easy_02,
  p_tennis_hard_01,
  p_tennis_large_01,
  p_tennis_medium_01,
  p_tennis_medium_02,
  p_thanksgiving_easy_01,
  p_thanksgiving_easy_02,
  p_thanksgiving_easy_03,
  p_thanksgiving_hard_01,
  p_thanksgiving_hard_02,
  p_thanksgiving_large_01,
  p_thanksgiving_large_02,
  p_thanksgiving_medium_01,
  p_thanksgiving_medium_02,
  p_thanksgiving_medium_03,
  p_tools_easy_01,
  p_tools_easy_02,
  p_tools_hard_01,
  p_tools_large_01,
  p_tools_medium_01,
  p_tools_medium_02,
  p_trains_easy_01,
  p_trains_easy_02,
  p_trains_hard_01,
  p_trains_large_01,
  p_trains_medium_01,
  p_trains_medium_02,
  p_travel_easy_01,
  p_travel_easy_02,
  p_travel_hard_01,
  p_travel_large_01,
  p_travel_medium_01,
  p_travel_medium_02,
  p_trees_easy_01,
  p_trees_easy_02,
  p_trees_hard_01,
  p_trees_large_01,
  p_trees_medium_01,
  p_trees_medium_02,
  p_us_states_easy_01,
  p_us_states_easy_02,
  p_us_states_hard_01,
  p_us_states_large_01,
  p_us_states_medium_01,
  p_us_states_medium_02,
  p_valentines_easy_01,
  p_valentines_easy_02,
  p_valentines_hard_01,
  p_valentines_large_01,
  p_valentines_medium_01,
  p_valentines_medium_02,
  p_vegetables_easy_01,
  p_vegetables_easy_02,
  p_vegetables_hard_01,
  p_vegetables_large_01,
  p_vegetables_medium_01,
  p_vegetables_medium_02,
  p_volcanoes_easy_01,
  p_volcanoes_easy_02,
  p_volcanoes_hard_01,
  p_volcanoes_large_01,
  p_volcanoes_medium_01,
  p_volcanoes_medium_02,
  p_weather_easy_01,
  p_weather_easy_02,
  p_weather_hard_01,
  p_weather_large_01,
  p_weather_medium_01,
  p_weather_medium_02,
  p_wedding_easy_01,
  p_wedding_easy_02,
  p_wedding_hard_01,
  p_wedding_large_01,
  p_wedding_medium_01,
  p_wedding_medium_02,
  p_winter_easy_01,
  p_winter_easy_02,
  p_winter_easy_03,
  p_winter_hard_01,
  p_winter_hard_02,
  p_winter_large_01,
  p_winter_large_02,
  p_winter_medium_01,
  p_winter_medium_02,
  p_winter_medium_03,
  p_world_capitals_easy_01,
  p_world_capitals_easy_02,
  p_world_capitals_hard_01,
  p_world_capitals_large_01,
  p_world_capitals_medium_01,
  p_world_capitals_medium_02,
  p_yoga_easy_01,
  p_yoga_easy_02,
  p_yoga_hard_01,
  p_yoga_large_01,
  p_yoga_medium_01,
  p_yoga_medium_02,
] as Puzzle[];
