export const SITE = {
  name: "Words at Rest",
  domain: "wordsatrest.com",
  url: (process.env.SITE_URL || "https://wordsatrest.com").replace(/\/$/, ""),
  tagline: "Calm, free word search puzzles for adults — large print, daily and seasonal.",
  /** Contact inbox — enable Cloudflare Email Routing (or Workspace) before AdSense. */
  contactEmail: "hello@wordsatrest.com",
  /**
   * First official date in the Daily archive (UTC, YYYY-MM-DD).
   * Dates before this 404; sitemap/archive never list pre-launch days.
   * Launch day (Asia/Shanghai calendar): 2026-10-06. Override with env DAILY_START.
   */
  dailyStart: process.env.DAILY_START || "2026-10-06",
  lastUpdatedLegal: "October 6, 2026",
  /** Visible "Updated" date on content hubs (ISO). Bump when hub copy changes. */
  contentUpdated: "2026-10-06",
  /**
   * Named editor for E-E-A-T (About page, bylines, Person schema).
   * Edit name/bio here; keep claims factual (no invented credentials).
   */
  editor: {
    name: "Reggie J",
    role: "Editor and publisher",
    aboutPath: "/about#editor",
  },
  /** Brand logo (raster, for Organization schema). Generated by scripts/generate-og.mjs. */
  logo: "/logo.png",
  /** Default social card (1200×630). Generated by scripts/generate-og.mjs. */
  ogImage: "/og/default.jpg",
  /**
   * Official social profiles for Organization.sameAs. Leave EMPTY until real
   * profiles exist — never invent URLs. e.g. ["https://x.com/wordsatrest"].
   */
  sameAs: [] as string[],
};

export function absoluteUrl(path: string): string {
  return `${SITE.url}${path.startsWith("/") ? path : `/${path}`}`;
}
