export const SITE = {
  name: "Words at Rest",
  domain: "wordsatrest.com",
  url: (process.env.SITE_URL || "https://wordsatrest.com").replace(/\/$/, ""),
  tagline: "Calm, free word search puzzles for adults — large print, daily and seasonal.",
  /** Contact inbox — enable Cloudflare Email Routing (or Workspace) before AdSense. */
  contactEmail: "hello@wordsatrest.com",
  /**
   * First official date in the Daily archive (UTC, YYYY-MM-DD).
   * Dates before this 404; sitemap/archive never list pre-launch days.
   * Launch day (Asia/Shanghai calendar): 2026-10-06. Override with env DAILY_START.
   */
  dailyStart: process.env.DAILY_START || "2026-10-06",
  lastUpdatedLegal: "October 6, 2026",
  /** Visible "Updated" date on content hubs (ISO). Bump when hub copy changes. */
  contentUpdated: "2026-10-06",
  /**
   * Named editor for E-E-A-T (About page, bylines, Person schema).
   * Edit name/bio here; keep claims factual (no invented credentials).
   */
  editor: {
    name: "Reggie J",
    role: "Editor and publisher",
    aboutPath: "/about#editor",
    /**
     * The editor's own public profiles (Person.sameAs). Only add URLs that are
     * really Reggie J's (e.g. a personal site, LinkedIn, X). Never invent them.
     */
    sameAs: ["https://x.com/0xReggieJ"] as string[],
  },
  /**
   * GA4 Measurement ID (public — it ships in every page's HTML anyway). Set here so
   * every build includes it; env NEXT_PUBLIC_GA_ID overrides (set it to "off" to
   * build without analytics, e.g. for local QA). A valid ID loads only after consent.
   */
  gaId: (process.env.NEXT_PUBLIC_GA_ID?.trim() || "G-QQWT6H8H2S") as string,
  /** Microsoft Clarity project ID; loaded only after optional analytics consent. */
  clarityId: (process.env.NEXT_PUBLIC_CLARITY_ID?.trim() || "yubihvuzyv") as string,
  /** Site language (BCP 47) — used for <html lang>, schema inLanguage, manifest. */
  language: "en-US",
  /** Open Graph locale form of `language`. */
  ogLocale: "en_US",
  /** Brand logo (raster, for Organization schema). Generated by scripts/generate-og.mjs. */
  logo: "/logo.png",
  /** Default social card (1200×630). Generated by scripts/generate-og.mjs. */
  ogImage: "/og/default.jpg",
  /**
   * Official profiles of the site itself — the ONE place to add them. Drives
   * Organization.sameAs in JSON-LD. Only real URLs; never invent profiles.
   * Add e.g. { label: "Pinterest", url: "https://www.pinterest.com/wordsatrest/" }
   * when the account exists. `footer: true` also lists it in the site footer.
   */
  profiles: [
    { label: "GitHub", url: "https://github.com/jiayixuan1009/words-at-rest", footer: false },
  ] as { label: string; url: string; footer?: boolean }[],
};

/** Organization.sameAs, derived from SITE.profiles. */
export const ORG_SAME_AS: string[] = SITE.profiles.map((p) => p.url);

export function absoluteUrl(path: string): string {
  return `${SITE.url}${path.startsWith("/") ? path : `/${path}`}`;
}
