/**
 * Top up the daily puzzle schedule to DAILY_TARGET_BUFFER_DAYS future days
 * beyond today UTC (first schedulable date: 2026-10-07).
 *
 * Each UTC date targets DAILY_PER_DATE (10) puzzles:
 *   - slot 1 = featured (/daily, homepage, calendar highlight)
 *   - slots 2–10 = "Also today" siblings
 * New entries are also written as theme-catalog puzzles under data/puzzles/
 * with ids `{theme}-{difficulty}-{nn}` and the puzzle registry is rebuilt.
 *
 * Already-public entries are never overwritten. Past dates (< today) with a
 * single legacy entry stay at 1; today and future dates are topped up to 10.
 *
 * Usage: npm run daily:add
 * Optional: DAILY_TODAY=YYYY-MM-DD to simulate "today" (UTC).
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateGrid, createRng } from "../lib/engine.ts";
import type { Difficulty, Puzzle, Theme } from "../lib/types.ts";
import {
  DAILY_PER_DATE,
  DAILY_TARGET_BUFFER_DAYS,
  DAILY_DIFFICULTY_PATTERN,
  DAILY_EXCLUDED_THEMES,
  DAILY_MAX_WORD_OVERLAP,
  DAILY_SCHEDULE_START,
  DAILY_SIZES,
  DAILY_THEME_GAP_DAYS,
  DAILY_WORD_COUNTS,
  addUtcDays,
  compareDailyEntries,
  dailySlotOf,
  dailyTitle,
  difficultyForDailySlot,
  gridFingerprint,
  isLegacyDailyId,
  listDatesInclusive,
  rankDailyThemes,
  wordSetOverlap,
  type DailyEntry,
  type DailyScheduleFile,
} from "../lib/daily.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schedulePath = join(root, "data/daily.json");
const themesDir = join(root, "data/themes");
const puzzlesDir = join(root, "data/puzzles");

function todayUtc(): string {
  return (process.env.DAILY_TODAY || new Date().toISOString().slice(0, 10)).slice(0, 10);
}

function loadSchedule(): DailyScheduleFile {
  const raw = JSON.parse(readFileSync(schedulePath, "utf8")) as DailyScheduleFile;
  if (raw.version !== 1 || !Array.isArray(raw.entries)) {
    throw new Error("data/daily.json: expected { version: 1, entries: [] }");
  }
  return raw;
}

function loadThemes(): Map<string, Theme> {
  const map = new Map<string, Theme>();
  for (const f of readdirSync(themesDir).filter((x) => x.endsWith(".json"))) {
    const t = JSON.parse(readFileSync(join(themesDir, f), "utf8")) as Theme;
    map.set(t.id, t);
  }
  return map;
}

function loadCatalogPuzzles(): Puzzle[] {
  return readdirSync(puzzlesDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(join(puzzlesDir, f), "utf8")) as Puzzle);
}

/** Next `{theme}-{difficulty}-{nn}` serial (nn is 01-based, max of on-disk + working). */
function nextCatalogSerial(
  themeId: string,
  difficulty: Difficulty,
  catalog: Puzzle[],
  working: DailyEntry[],
): number {
  const prefix = `${themeId}-${difficulty}-`;
  let max = 0;
  const consider = (id: string) => {
    if (!id.startsWith(prefix)) return;
    const n = Number(id.slice(prefix.length));
    if (Number.isFinite(n) && n > max) max = n;
  };
  for (const p of catalog) consider(p.id);
  for (const e of working) consider(e.id);
  // Also scan filenames in case registry lags
  for (const f of readdirSync(puzzlesDir).filter((x) => x.endsWith(".json"))) {
    consider(f.replace(/\.json$/, ""));
  }
  return max + 1;
}

function dateSlotSeed(date: string, slot: number): number {
  let h = 2166136261;
  for (const ch of `daily:${date}:slot:${slot}`) h = Math.imul(h ^ ch.charCodeAt(0), 16777619);
  return (h >>> 0) || 1;
}

/** Themes to avoid: any slot in previous `gap` days, plus featured themes in the next `gap` days. */
function blockedThemes(entries: DailyEntry[], aroundDate: string, gap: number): string[] {
  const out: string[] = [];
  for (let i = 1; i <= gap; i++) {
    const prev = addUtcDays(aroundDate, -i);
    const next = addUtcDays(aroundDate, i);
    for (const e of entries) {
      if (e.date === prev) out.push(e.themeId);
      if (e.date === next && (e.featured === true || (e.slot ?? 1) === 1)) out.push(e.themeId);
    }
  }
  return out;
}

function entriesForDate(entries: DailyEntry[], date: string): DailyEntry[] {
  return entries.filter((e) => e.date === date).sort(compareDailyEntries);
}

function rebuildPuzzleRegistry(): number {
  const slugs = readdirSync(puzzlesDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""))
    .sort((a, b) => a.localeCompare(b));
  const ident = (s: string) => "p_" + s.replace(/-/g, "_");
  const registry =
    "// AUTO-GENERATED by scripts/generate-puzzles.ts / add-daily.ts — do not edit by hand.\n" +
    'import type { Puzzle } from "../../lib/types";\n' +
    slugs.map((s) => `import ${ident(s)} from "./${s}.json";`).join("\n") +
    "\n\nexport const puzzles = [\n" +
    slugs.map((s) => `  ${ident(s)},`).join("\n") +
    "\n] as Puzzle[];\n";
  writeFileSync(join(puzzlesDir, "index.ts"), registry);
  return slugs.length;
}

function catalogTitle(entry: DailyEntry, themeName: string): string {
  const label = entry.difficulty.charAt(0).toUpperCase() + entry.difficulty.slice(1);
  const m = entry.id.match(/-(\d+)$/);
  const nn = m ? m[1] : String(entry.slot ?? 1).padStart(2, "0");
  // Unique vs creative catalog titles ("Theme: …") and across daily siblings.
  return `${themeName} Word Search (${label}) #${nn}`;
}

function writeCatalogPuzzle(entry: DailyEntry, themeName: string): void {
  if (isLegacyDailyId(entry.id, entry.date)) return; // legacy daily-* stays schedule-only
  const puzzle: Puzzle = {
    id: entry.id,
    slug: entry.slug,
    themeId: entry.themeId,
    title: catalogTitle(entry, themeName),
    primaryKeyword: entry.primaryKeyword.replace(/^daily /, ""),
    difficulty: entry.difficulty,
    gridSize: entry.gridSize,
    largePrint: false,
    words: entry.words,
    grid: entry.grid,
    placements: entry.placements,
    createdAt: entry.createdAt.slice(0, 10),
    seed: entry.seed,
  };
  const outPath = join(puzzlesDir, `${entry.id}.json`);
  if (existsSync(outPath)) {
    throw new Error(`catalog file already exists: ${entry.id}.json`);
  }
  writeFileSync(outPath, JSON.stringify(puzzle, null, 2) + "\n");
}

function generateOne(
  date: string,
  slot: number,
  themes: Map<string, Theme>,
  catalog: Puzzle[],
  existing: DailyEntry[],
): DailyEntry {
  const difficulty = difficultyForDailySlot(date, slot);
  const size = DAILY_SIZES[difficulty];
  const count = DAILY_WORD_COUNTS[difficulty];
  const sameDayThemes = new Set(entriesForDate(existing, date).map((e) => e.themeId));
  const themeIds = [...themes.keys()].filter((id) => !DAILY_EXCLUDED_THEMES.has(id));
  const ranked = rankDailyThemes(
    date,
    themeIds,
    [...blockedThemes(existing, date, DAILY_THEME_GAP_DAYS), ...sameDayThemes],
  ).filter((id) => !sameDayThemes.has(id));
  if (!ranked.length) {
    throw new Error(`${date} slot ${slot}: no theme candidates after gap/same-day filter`);
  }

  const existingFingerprints = new Set([
    ...catalog.map((p) => gridFingerprint(p.grid)),
    ...existing.map((e) => gridFingerprint(e.grid)),
  ]);

  const baseSeed = dateSlotSeed(date, slot);
  let lastErr = "";

  for (let themeIdx = 0; themeIdx < ranked.length; themeIdx++) {
    const themeId = ranked[themeIdx];
    const theme = themes.get(themeId)!;
    const sameThemeWords = [
      ...catalog.filter((p) => p.themeId === themeId).map((p) => p.words),
      ...existing.filter((e) => e.themeId === themeId).map((e) => e.words),
    ];

    for (let attempt = 0; attempt < 40; attempt++) {
      const seed = baseSeed + themeIdx * 1009 + attempt * 17;
      const rng = createRng(seed * 7 + 13);
      const pool = theme.words
        .map((w) => w.toUpperCase().replace(/[^A-Z]/g, ""))
        .filter((w) => w.length >= 3 && w.length <= size);
      const shuffled = [...pool].sort(() => rng() - 0.5);
      const chosen = shuffled.slice(0, count);
      if (chosen.length < count) {
        lastErr = `${themeId}: bank too small for ${difficulty}`;
        break;
      }

      let tooSimilar = false;
      for (const other of sameThemeWords) {
        if (wordSetOverlap(chosen, other) >= DAILY_MAX_WORD_OVERLAP) {
          tooSimilar = true;
          break;
        }
      }
      if (tooSimilar) {
        lastErr = `${themeId}: word overlap ≥ ${DAILY_MAX_WORD_OVERLAP}`;
        continue;
      }

      const { grid, placements, skipped } = generateGrid({
        words: chosen,
        size,
        difficulty,
        seed,
      });
      if (skipped.length || placements.length < count) {
        lastErr = `${themeId}: placed ${placements.length}/${count}, skipped ${skipped.join(",")}`;
        continue;
      }
      const fp = gridFingerprint(grid);
      if (existingFingerprints.has(fp)) {
        lastErr = `${themeId}: duplicate grid`;
        continue;
      }

      const words = placements.map((p) => p.word).sort();
      for (const other of sameThemeWords) {
        if (wordSetOverlap(words, other) >= DAILY_MAX_WORD_OVERLAP) {
          tooSimilar = true;
          break;
        }
      }
      if (tooSimilar) continue;

      const serial = nextCatalogSerial(themeId, difficulty, catalog, existing);
      const id = `${themeId}-${difficulty}-${String(serial).padStart(2, "0")}`;
      const nn = String(serial).padStart(2, "0");
      const label = difficulty.charAt(0).toUpperCase() + difficulty.slice(1);
      const title =
        slot === 1
          ? dailyTitle(theme.name, difficulty, slot)
          : `${theme.name} Word Search (${label}) #${nn}`;
      return {
        date,
        slot,
        featured: slot === 1,
        id,
        slug: id,
        themeId,
        difficulty,
        title,
        primaryKeyword: slot === 1 ? `daily ${theme.primaryKeyword}` : theme.primaryKeyword,
        gridSize: size,
        largePrint: false,
        words,
        grid,
        placements,
        seed,
        createdAt: new Date().toISOString(),
      };
    }
  }

  throw new Error(`${date} slot ${slot}: failed to generate (${lastErr})`);
}

function targetSlotsForDate(date: string, today: string): number {
  // Past dates: keep whatever exists (do not force 10).
  if (date < today) return 0; // 0 = "do not top up"
  return DAILY_PER_DATE;
}

function main() {
  const today = todayUtc();
  const horizon = addUtcDays(today, DAILY_TARGET_BUFFER_DAYS);
  const needed = listDatesInclusive(DAILY_SCHEDULE_START, horizon);

  const schedule = loadSchedule();
  schedule.difficultyPattern =
    DAILY_DIFFICULTY_PATTERN +
    `; ${DAILY_PER_DATE}/day (slot 1 = weekday pattern; slots 2–10 cycle easy/medium/hard)`;
  const themes = loadThemes();
  let catalog = loadCatalogPuzzles();

  const working = [...schedule.entries].sort(compareDailyEntries);
  const added: DailyEntry[] = [];
  let wroteCatalog = 0;

  for (const date of needed) {
    const target = targetSlotsForDate(date, today);
    if (target === 0) continue;
    const have = entriesForDate(working, date);
    // Ensure legacy single entries are treated as slot 1
    for (const e of have) {
      if (e.slot == null) {
        e.slot = 1;
        e.featured = true;
      }
    }
    const usedSlots = new Set(have.map((e) => dailySlotOf(e)));
    // If somehow no featured, we still fill missing slots 1..target
    for (let slot = 1; slot <= target; slot++) {
      if (usedSlots.has(slot)) continue;
      const entry = generateOne(date, slot, themes, catalog, working);
      const themeName = themes.get(entry.themeId)?.name ?? entry.themeId;
      writeCatalogPuzzle(entry, themeName);
      wroteCatalog++;
      // Keep catalog in memory so next serial / fingerprints see it
      catalog.push({
        id: entry.id,
        slug: entry.slug,
        themeId: entry.themeId,
        title: entry.title,
        primaryKeyword: entry.primaryKeyword,
        difficulty: entry.difficulty,
        gridSize: entry.gridSize,
        largePrint: false,
        words: entry.words,
        grid: entry.grid,
        placements: entry.placements,
        createdAt: entry.createdAt.slice(0, 10),
        seed: entry.seed,
      });
      working.push(entry);
      working.sort(compareDailyEntries);
      added.push(entry);
      console.log(
        `+ ${date}#${slot}  ${entry.title}  id=${entry.id}  theme=${entry.themeId}  ${entry.difficulty}  seed=${entry.seed}`,
      );
    }
  }

  // Annotate existing single-slot rows (today+) with slot/featured without rewriting grids
  for (const e of working) {
    if (e.date >= today && e.slot == null) {
      e.slot = 1;
      e.featured = true;
    }
  }

  if (!added.length) {
    console.log(
      `daily:add — buffer full through ${horizon} (today ${today}, ${DAILY_PER_DATE}/day); nothing to do`,
    );
    return;
  }

  schedule.entries = working.sort(compareDailyEntries);
  writeFileSync(schedulePath, JSON.stringify(schedule, null, 2) + "\n");
  const regCount = rebuildPuzzleRegistry();
  console.log(
    `wrote ${added.length} schedule entr${added.length === 1 ? "y" : "ies"} (${wroteCatalog} catalog files) → data/daily.json; registry ${regCount} puzzles (through ${horizon})`,
  );
}

try {
  main();
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}
